'use client';
import {createContext,useContext,useEffect,useState,type ReactNode} from 'react';

type Language='ht'|'fr';
const copy={
 ht:{dashboard:'Tablo de bò',sell:'Vann bolet',check:'Verifye / Peye',history:'Tikè yo',results:'Rezilta',cash:'Kès',printer:'Enprimant',logout:'Dekonekte',online:'Sou entènèt',offline:'San entènèt',loading:'Tanpri tann…',sales:'Vant jodi a',tickets:'Tikè',payouts:'Peman gayan',commission:'Komisyon',shift:'Jounen travay',recent:'Dènye tikè',reload:'Rechaje',open:'Ouvè',closed:'Fèmen',none:'Okenn',print:'Enprime tikè',search:'Chèche',ticketCheck:'Verifye tikè',ticketNumber:'Nimewo tikè / kòd',cancel:'Anile tikè',copy:'Kopye / Rejwe',amount:'Montan',potential:'Gany posib',draw:'Tiraj',noResults:'Pa gen rezilta pibliye.',live:'Rezilta an tan reyèl',updates:'Mizajou chak 15 segonn',login:'Koneksyon machann',intro:'Administratè biznis la kreye kont ou.',tenant:'Espas biznis',username:'Non itilizatè / Telefòn',password:'Modpas',submit:'Konekte',forgot:'Ou bliye modpas la?',pay:'Peye gayan',status:'Estati',opening:'Kès kòmansman',movements:'Mouvman',printerQueue:'Travay enpresyon',refresh:'Rafrechi',newTicket:'Nouvo tikè',openDraw:'Tiraj ouvè',validate:'Valide epi vann',addBet:'Ajoute jwèt',total:'Total',date:'Dat',sellHelp:'Antre boul la ak pri li. 2 chif se Bolet; 3, 4 oswa 5 chif se Loto.',choose:'Chwazi tiraj',autoPrint:'Pa gen enpresyon otomatik',template:'Modèl tikè',ball:'Boul',ballPrice:'Pri boul sa a',addBall:'Ajoute boul',lotoOnly:'Opsyon Loto sèlman',allOptions:'Tout opsyon',allPrice:'Pri pou tout liy',applyPrice:'Aplike pri sou tout',marriage:'Maryaj ak bolet yo',autoLoto:'Loto otomatik ak bolet yo',pair:'Boul pè 00–99',autoHelp:'Maryaj ak Loto otomatik itilize boul 2 chif ki sou tikè a. Loto 3 ak Loto 5 rete manyèl.',price:'Pri',option:'Opsyon',type:'Kalite',reason:'Rezon',addMovement:'Ajoute mouvman',closeShift:'Fèmen kès',openShift:'Ouvri kès',actualCash:'Kès reyèl',permissionCash:'Ou pa gen pèmisyon pou gade kès la.',attempts:'Eseye'},
 fr:{dashboard:'Tableau de bord',sell:'Vente de tickets',check:'Vérifier / Payer',history:'Tickets',results:'Résultats',cash:'Caisse',printer:'Imprimantes',logout:'Déconnexion',online:'En ligne',offline:'Hors ligne',loading:'Veuillez patienter…',sales:'Ventes du jour',tickets:'Tickets',payouts:'Paiements',commission:'Commission',shift:'Session de caisse',recent:'Tickets récents',reload:'Actualiser',open:'Ouverte',closed:'Fermée',none:'Aucun',print:'Imprimer le ticket',search:'Rechercher',ticketCheck:'Vérifier un ticket',ticketNumber:'Numéro du ticket / code',cancel:'Annuler le ticket',copy:'Copier / Rejouer',amount:'Montant',potential:'Gain potentiel',draw:'Tirage',noResults:'Aucun résultat publié.',live:'Résultats en direct',updates:'Actualisation toutes les 15 secondes',login:'Connexion vendeur',intro:'Votre administrateur crée votre compte.',tenant:'Espace professionnel',username:'Identifiant / Téléphone',password:'Mot de passe',submit:'Se connecter',forgot:'Mot de passe oublié ?',pay:'Payer le gagnant',status:'Statut',opening:'Fond de caisse',movements:'Mouvements',printerQueue:'File d’impression',refresh:'Actualiser',newTicket:'Nouveau ticket',openDraw:'Tirage ouvert',validate:'Valider et vendre',addBet:'Ajouter un jeu',total:'Total',date:'Date',sellHelp:'Saisissez le numéro et sa mise. 2 chiffres : Bolet ; 3, 4 ou 5 chiffres : Loto.',choose:'Sélectionnez un tirage',autoPrint:'Pas d’impression automatique',template:'Modèle de ticket',ball:'Numéro',ballPrice:'Mise pour ce numéro',addBall:'Ajouter le numéro',lotoOnly:'Options Loto uniquement',allOptions:'Toutes les positions',allPrice:'Mise pour toutes les lignes',applyPrice:'Appliquer la mise à toutes les lignes',marriage:'Mariage des numéros Bolet',autoLoto:'Loto automatique avec Bolet',pair:'Paires 00–99',autoHelp:'Les combinaisons automatiques utilisent les numéros à 2 chiffres de ce ticket. Loto 3 et Loto 5 restent manuels.',price:'Mise',option:'Position',type:'Type',reason:'Motif',addMovement:'Ajouter un mouvement',closeShift:'Fermer la caisse',openShift:'Ouvrir la caisse',actualCash:'Caisse constatée',permissionCash:'Vous n’avez pas accès à la caisse.',attempts:'Tentatives'}
} as const;
type Key=keyof typeof copy.ht;
const LanguageContext=createContext<{language:Language;t:(key:Key)=>string}>({language:'ht',t:key=>copy.ht[key]});
export const useMerchantLanguage=()=>useContext(LanguageContext);
export function statusLabel(value:string,language:Language){
 const labels:Record<string,[string,string]>={VALID:['Valab','Valide'],WINNER:['Gayan','Gagnant'],LOSER:['Pèdan','Perdant'],PAID:['Peye','Payé'],CANCELLED:['Anile','Annulé'],VOID:['Anile','Annulé'],OPEN:['Ouvè','Ouvert'],CLOSED:['Fèmen','Fermé'],ONLINE:['Sou entènèt','En ligne'],OFFLINE:['San entènèt','Hors ligne'],PENDING:['An atant','En attente'],PRINTED:['Enprime','Imprimé'],QUEUED:['Nan fil la','En attente'],FAILED:['Echwe','Échec']};
 return labels[value]?.[language==='fr'?1:0]??value;
}

export function LanguageSwitcher({children}:{children:ReactNode}){
 const[language,setLanguage]=useState<Language>('ht');
 useEffect(()=>{try{if(localStorage.getItem('lottivexa-language')==='fr')setLanguage('fr')}catch{}},[]);
 useEffect(()=>{document.documentElement.lang=language;try{localStorage.setItem('lottivexa-language',language)}catch{}},[language]);
 return <LanguageContext.Provider value={{language,t:key=>copy[language][key]}}><div data-language-switcher className="languageSwitcher" role="group" aria-label="Lang / Langue"><button type="button" aria-pressed={language==='ht'} className={language==='ht'?'active':''} onClick={()=>setLanguage('ht')}>Kreyòl</button><button type="button" aria-pressed={language==='fr'} className={language==='fr'?'active':''} onClick={()=>setLanguage('fr')}>Français</button></div>{children}</LanguageContext.Provider>
}
