'use client';
import{FormEvent,useCallback,useEffect,useMemo,useState}from'react';import'./styles.css';
import PrintReceipt from './print-receipt';
import {useMerchantLanguage,statusLabel} from './language-switcher';
import {drawLabel} from './draw-label';
const API=process.env.NEXT_PUBLIC_API_URL??'http://localhost:4000/api/v1';const RESET_URL=process.env.NEXT_PUBLIC_PASSWORD_RESET_URL??'https://lottivexa-public-site.onrender.com/reset-password';type Row=Record<string,any>;type Screen='dashboard'|'sell'|'check'|'history'|'results'|'cash'|'printer';type BetLine={betTypeId:string;selection:string;stake:string;resultPosition?:number;betName?:string};
function form(e:HTMLFormElement){return Object.fromEntries(new FormData(e))as Row}function id(){return crypto.randomUUID()}function cash(v:any){return new Intl.NumberFormat(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v??0))}function jwt(t:string){try{return JSON.parse(atob(t.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')))}catch{return{permissions:[]}}}
export default function MerchantPos(){const{t}=useMerchantLanguage();const[token,setToken]=useState(''),[refresh,setRefresh]=useState(''),[force,setForce]=useState(false),[screen,setScreen]=useState<Screen>('dashboard'),[state,setState]=useState<Row>({}),[selected,setSelected]=useState<Row|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[online,setOnline]=useState(true),[lines,setLines]=useState<BetLine[]>([{betTypeId:'',selection:'',stake:''}]);const permissions=useMemo<string[]>(()=>jwt(token).permissions??[],[token]),can=(p:string)=>permissions.includes(p);
 useEffect(()=>{setToken(localStorage.getItem('merchant_access')??'');setRefresh(localStorage.getItem('merchant_refresh')??'');setForce(localStorage.getItem('merchant_force')==='true');const status=()=>setOnline(navigator.onLine);status();addEventListener('online',status);addEventListener('offline',status);return()=>{removeEventListener('online',status);removeEventListener('offline',status)}},[]);
 const logout=useCallback(()=>{for(const k of['merchant_access','merchant_refresh','merchant_force'])localStorage.removeItem(k);setToken('');setRefresh('');setState({});setSelected(null)},[]);
 const request=useCallback(async(path:string,init:RequestInit={})=>{let access=localStorage.getItem('merchant_access')??token;const send=()=>fetch(`${API}${path}`,{...init,headers:{'content-type':'application/json',authorization:`Bearer ${access}`,...init.headers}});let r=await send();if(r.status===401&&refresh){const renewed=await fetch(`${API}/auth/refresh`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({refreshToken:refresh})});if(renewed.ok){const n=await renewed.json();access=n.accessToken;localStorage.setItem('merchant_access',n.accessToken);localStorage.setItem('merchant_refresh',n.refreshToken);setToken(n.accessToken);setRefresh(n.refreshToken);r=await send()}else logout()}const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.code??body.message??`HTTP_${r.status}`);return body},[token,refresh,logout]);
 const run=useCallback(async(fn:()=>Promise<any>,ok?:string)=>{setBusy(true);setMessage('');try{const result=await fn();if(ok)setMessage(ok);return result}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}},[]);
 const load=useCallback(async()=>{const result=await run(async()=>{const[d,g,p,t,j,c]=await Promise.all([request('/merchants/me/dashboard'),request('/lottery/games'),can('printers.view')?request('/printing/printers'):[],can('printers.view')?request('/printing/templates'):[],can('printers.view')?request('/printing/jobs'):[],can('finance.view')?request('/cash/session/current'):null]);return{dashboard:d,games:g,draws:(await request('/lottery/draws')).filter((x:Row)=>x.status==='OPEN'),printers:p,templates:t,jobs:j,session:c}});if(result)setState(result)},[request,run,permissions.join('|')]);
 useEffect(()=>{if(!token||force)return;void load();const timer=setInterval(()=>void load(),60000);return()=>clearInterval(timer)},[token,force,load]);
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();const result=await run(async()=>{const r=await fetch(`${API}/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form(e.currentTarget))}),body=await r.json();if(!r.ok)throw new Error(body.code??body.message??'INVALID_CREDENTIALS');return body},'Koneksyon reyisi.');if(result){localStorage.setItem('merchant_access',result.accessToken);localStorage.setItem('merchant_refresh',result.refreshToken);localStorage.setItem('merchant_force',String(result.forcePasswordChange));setToken(result.accessToken);setRefresh(result.refreshToken);setForce(result.forcePasswordChange)}}
 async function mutate(path:string,body:Row,ok:string){const result=await run(()=>request(path,{method:'POST',body:JSON.stringify(body)}),ok);if(result)await load();return result}
 const gameForDraw=(drawId:string)=>{const draw=state.draws?.find((x:Row)=>x.id===drawId);return state.games?.find((x:Row)=>x.id===draw?.gameId)};
 async function sell(e:FormEvent<HTMLFormElement>){e.preventDefault();const meta=form(e.currentTarget),payload={drawId:meta.drawId,deviceId:meta.deviceId||undefined,idempotencyKey:id(),lines:lines.map(x=>({betTypeId:x.betTypeId,selection:x.selection.split(/[ ,.-]+/).filter(Boolean),stake:x.stake,resultPosition:x.resultPosition}))};const ticket=await mutate('/tickets',payload,'Tikè kreye epi sove.');if(ticket){setSelected(ticket);setLines([]);if(meta.printerId&&meta.templateId)await mutate('/printing/jobs',{ticketId:ticket.id,printerId:meta.printerId,templateId:meta.templateId,idempotencyKey:`print:${ticket.id}:${id()}`},'Tikè kreye; print job antre nan queue.');setScreen('check')}}
 async function lookup(e:FormEvent<HTMLFormElement>){e.preventDefault();const ref=String(form(e.currentTarget).reference),ticket=await run(()=>request(`/tickets/${encodeURIComponent(ref)}`));if(ticket)setSelected(ticket)}
 async function lookupTicket(reference:string){const ticket=await run(()=>request(`/tickets/${encodeURIComponent(reference)}`));if(ticket){setSelected(ticket);setScreen('check')}}
 async function pay(){if(selected)await mutate('/payouts',{ticketReference:selected.ticketNumber,idempotencyKey:id()},'Payout otorize; ledger ajiste.').then(async r=>{if(r)setSelected(await request(`/tickets/${selected.ticketNumber}`))})}
 async function cancel(){if(selected)await mutate(`/tickets/${encodeURIComponent(selected.ticketNumber)}/cancel`,{},'Ticket anile; sale ak commission ranvèse.').then(r=>r&&setSelected(r))}
 async function printTicket(){if(!selected)return;try{const ticket=await request(`/tickets/${encodeURIComponent(selected.ticketNumber)}`);setSelected(ticket);requestAnimationFrame(()=>requestAnimationFrame(()=>window.print()));}catch(e){setMessage(e instanceof Error?e.message:String(e))}}
 if(!token)return <main className="login"><h1>LOTTIVEXA</h1><h2>{t('login')}</h2><p>{t('intro')}</p><form onSubmit={login}><label>{t('tenant')}<input name="tenant" required/></label><label>{t('username')}<input name="username" required/></label><label>{t('password')}<input name="password" type="password" minLength={8} required/></label><button disabled={busy}>{t('submit')}</button></form><a href={RESET_URL}>{t('forgot')}</a>{message&&<p className="message">{message}</p>}</main>;
 if(force)return <main className="login"><h1>{t('forcePassword')}</h1><form onSubmit={async e=>{e.preventDefault();const result=await mutate('/users/me/change-password',form(e.currentTarget),'Modpas chanje. Konekte ankò.');if(result)setTimeout(logout,700)}}><label>{t('currentPassword')}<input name="currentPassword" type="password" required/></label><label>{t('newPassword')}<input name="newPassword" type="password" minLength={12} required/></label><button>{t('changePassword')}</button></form><button className="secondary" onClick={logout}>{t('back')}</button>{message&&<p className="message">{message}</p>}</main>;
 function replayTicket(ticket:Row){setLines((ticket.lines??[]).map((line:Row)=>{const parts=String(line.selectionKey).split('@');return{betTypeId:line.betTypeId,selection:parts[0],stake:String(line.stake),resultPosition:Number(parts[1]||1),betName:line.betType?.name}}));setMessage("Tikè a kopye. Chwazi yon tiraj ki ouvè epi valide nouvo tikè a.");setScreen("sell")}
 const nav:[Screen,string][]=[['dashboard',t('dashboard')],['sell',t('sell')],['check',t('check')],['history',t('history')],['results',t('results')],['cash',t('cash')],['printer',t('printer')]];
 return <div className="pos"><header><div><b>{state.dashboard?.businessName??'Bolet'}</b><small>{state.dashboard?.merchant?.displayName??'Merchant'} · {state.dashboard?.merchant?.branch?.name??''}</small></div><div className={online?'online':'offline'}>● {online?t('online'):t('offline')}</div><button className="secondary" onClick={logout}>{t('logout')}</button></header><nav>{nav.map(x=><button className={screen===x[0]?'active':''} key={x[0]} onClick={()=>setScreen(x[0])}>{x[1]}</button>)}</nav><main>{message&&<p className="message">{message}</p>}{busy&&<div className="busy">{t('loading')}</div>}{screen==='dashboard'&&<Dashboard state={state} reload={load}/>} {screen==='sell'&&<HaitianPos state={state} lines={lines} setLines={setLines} gameForDraw={gameForDraw} submit={sell} online={online}/>} {screen==='check'&&<Check selected={selected} lookup={lookup} pay={pay} cancel={cancel} printTicket={printTicket} replay={replayTicket} can={can}/>} {screen==='history'&&<History rows={state.dashboard?.recent??[]} select={(x:Row)=>{void lookupTicket(x.ticketNumber)}}/>} {screen==='results'&&<LiveResults request={request}/>} {screen==='cash'&&<Cash session={state.session} mutate={mutate} can={can}/>} {screen==='printer'&&<Printer state={state} reload={load}/>}</main><PrintReceipt ticket={selected} businessName={state.dashboard?.businessName??'Bolet'} branchName={state.dashboard?.merchant?.branch?.name}/></div>
}
function Dashboard({state:s,reload}:any){const{t}=useMerchantLanguage();const d=s.dashboard??{},date=d.businessDate?new Date(`${d.businessDate}T12:00:00-04:00`).toLocaleDateString('fr-HT',{timeZone:'America/Port-au-Prince',dateStyle:'full'}):'';return <><section className="dashboard-welcome"><div><span className="eyebrow">{t('today')}</span><h2>{date}</h2></div><button className="secondary" onClick={reload}>{t('reload')}</button></section><div className="stats"><article><span>{t('sales')}</span><strong>{cash(d.sales)}</strong></article><article><span>{t('netSales')}</span><strong>{cash(Number(d.sales??0)-Number(d.payouts??0))}</strong></article><article><span>{t('tickets')}</span><strong>{d.ticketCount??0}</strong></article><article><span>{t('payouts')}</span><strong>{cash(d.payouts)}</strong></article><article><span>{t('commission')}</span><strong>{cash(d.commission)}</strong></article><article><span>{t('shift')}</span><strong>{d.session?t('open'):t('closed')}</strong></article><article><span>{t('printer')}</span><strong>{s.printers?.find((x:Row)=>x.isDefault)?.status??s.printers?.[0]?.status??t('none')}</strong></article></div><section className="panel"><div className="title"><h2>{t('recent')}</h2></div><History rows={d.recent??[]} select={()=>{}}/></section></>}
function Sell({state:s,lines,setLines,gameForDraw,submit,online}:any){const[draw,setDraw]=useState(s.draws?.[0]?.id??'');useEffect(()=>{if(!draw&&s.draws?.[0])setDraw(s.draws[0].id)},[s.draws]);const game=gameForDraw(draw),bets=game?.betTypes?.map((x:Row)=>x.betType)??[];return <section className="panel sell"><h2>New Ticket</h2><form onSubmit={submit}><div className="form-grid"><label>Open draw<select name="drawId" value={draw} onChange={e=>setDraw(e.target.value)} required><option value="">Select draw</option>{s.draws?.map((x:Row)=><option value={x.id} key={x.id}>{x.game?.name??x.drawNumber} — {x.drawNumber}</option>)}</select></label><label>Printer<select name="printerId"><option value="">No auto-print</option>{s.printers?.map((x:Row)=><option key={x.id} value={x.id}>{x.name} ({x.status})</option>)}</select></label><label>Ticket template<select name="templateId"><option value="">Select</option>{s.templates?.filter((x:Row)=>x.kind==='TICKET').map((x:Row)=><option key={x.id} value={x.id}>{x.name} v{x.version}</option>)}</select></label></div>{lines.map((line:BetLine,i:number)=><div className="bet-line" key={i}><label>Bet type<select value={line.betTypeId} onChange={e=>setLines(lines.map((x:BetLine,j:number)=>j===i?{...x,betTypeId:e.target.value}:x))} required><option value="">Select</option>{bets.map((x:Row)=><option key={x.id} value={x.id}>{x.name} ({x.selectionCount} number)</option>)}</select></label><label>Numbers<input value={line.selection} inputMode="numeric" placeholder="12 34" onChange={e=>setLines(lines.map((x:BetLine,j:number)=>j===i?{...x,selection:e.target.value}:x))} required/></label><label>Stake<input value={line.stake} type="number" min=".01" step=".01" onChange={e=>setLines(lines.map((x:BetLine,j:number)=>j===i?{...x,stake:e.target.value}:x))} required/></label><button type="button" className="danger" onClick={()=>setLines(lines.filter((_:BetLine,j:number)=>j!==i))}>×</button></div>)}<div className="ticket-actions"><button type="button" className="secondary" onClick={()=>setLines([...lines,{betTypeId:'',selection:'',stake:''}])}>+ Add bet</button><b>Total: {cash(lines.reduce((n:number,x:BetLine)=>n+Number(x.stake||0),0))}</b><button disabled={!online}>VALIDATE & SELL</button></div></form></section>}
function Check({selected:t,lookup,pay,cancel,printTicket,replay,can}:any){const{t:tr,language}=useMerchantLanguage();const verified=t?.status==='WINNER'&&Number(t?.winning?.winningAmount)>0&&(t?.lines??[]).some((line:Row)=>line.isWinner===true);return <><section className="panel"><h2>{tr('ticketCheck')}</h2><form className="lookup" onSubmit={lookup}><input name="reference" placeholder={tr('ticketNumber')} autoFocus required/><button>{tr('search')}</button></form></section>{t&&<section className="ticket"><div className="ticket-head"><h2>{t.ticketNumber}</h2><b className={String(t.status).toLowerCase()}>{t.status==='WINNER'&&!verified?(language==='fr'?'Vérification requise':'Bezwen verifikasyon'):statusLabel(t.status,language)}</b></div><p>{t.draw?drawLabel(t.draw,language):t.game?.name}</p>{t.lines?.map((x:Row)=><div className="ticket-line" key={x.id}><span>{x.betType?.name??'Bet'}: <b>{x.selectionKey}</b></span><span>{cash(x.stake)} → {cash(x.potentialWin)}</span></div>)}<div className="total"><span>{tr('amount')} <b>{cash(t.amount)}</b></span><span>{tr('potential')} <b>{cash(t.potentialWin)}</b></span></div>{verified&&<p className="winner">{language==='fr'?'Gain confirmé':'Gany konfime'}: {cash(t.winning.winningAmount)}</p>}<div className="buttons">{can('tickets.pay')&&verified&&!t.payout&&<button onClick={pay}>{tr('pay')}</button>}{can('tickets.cancel')&&t.status==='VALID'&&<button className="danger" onClick={cancel}>{tr('cancel')}</button>}<button className="secondary" onClick={()=>replay(t)}>{tr('copy')}</button>{can('tickets.reprint')&&<button className="secondary" onClick={printTicket}>{tr('print')}</button>}</div></section>}</>}
function History({rows,select}:{rows:Row[];select:(x:Row)=>void}){const{t,language}=useMerchantLanguage();return <div className="history">{rows.length?rows.map(x=><button key={x.id} onClick={()=>select(x)}><span><b>{x.ticketNumber}</b><small>{new Date(x.createdAt).toLocaleString()}</small></span><span><b>{cash(x.amount)}</b><small>{x.status==='WINNER'&&(!(Number(x.winning?.winningAmount)>0)||!(x.lines??[]).some((line:Row)=>line.isWinner===true))?(language==='fr'?'À vérifier':'Pou verifye'):statusLabel(x.status,language)}</small></span></button>):<p>{t('none')}</p>}</div>}
function Cash({session,mutate,can}:any){const{t,language}=useMerchantLanguage();if(!can('finance.view'))return <section className="panel"><h2>{t('cash')}</h2><p>{t('permissionCash')}</p></section>;return <section className="panel"><h2>{t('cash')}</h2>{session?<><div className="stats"><article><span>{t('status')}</span><strong>{statusLabel(session.status,language)}</strong></article><article><span>{t('opening')}</span><strong>{cash(session.openingCash)}</strong></article><article><span>{t('movements')}</span><strong>{session.movements?.length??0}</strong></article></div>{can('finance.adjust')&&<form className="form-grid" onSubmit={e=>{e.preventDefault();const x=form(e.currentTarget);void mutate(`/cash/session/${session.id}/movements`,{...x,idempotencyKey:id()},'Cash movement saved.');e.currentTarget.reset()}}><label>{t('type')}<select name="type"><option>CASH_IN</option><option>CASH_OUT</option><option>EXPENSE</option><option>DEPOSIT</option><option>WITHDRAWAL</option><option>ADJUSTMENT</option></select></label><label>{t('amount')}<input name="amount" type="number" min=".01" step=".01" required/></label><label>{t('reason')}<input name="reason" required/></label><button>{t('addMovement')}</button></form>}<form className="lookup" onSubmit={e=>{e.preventDefault();void mutate(`/cash/session/${session.id}/close`,form(e.currentTarget),'Shift closed; final difference calculated.')}}><input name="actualCash" type="number" step=".01" min="0" placeholder={t("actualCash")} required/><button className="danger">{t('closeShift')}</button></form></>:<form className="lookup" onSubmit={e=>{e.preventDefault();void mutate('/cash/session/open',form(e.currentTarget),'Shift opened.')}}><input name="openingCash" type="number" min="0" step=".01" placeholder="Opening cash" required/><button>{t('openShift')}</button></form>}</section>}
function Printer({state:s,reload}:any){const{t,language}=useMerchantLanguage();return <><div className="stats">{s.printers?.map((x:Row)=><article key={x.id}><span>{x.connectionType}</span><strong>{x.name}</strong><small>{statusLabel(x.status,language)}{x.isDefault?' · DEFAULT':''}</small></article>)}</div><section className="panel"><div className="title"><h2>{t('printerQueue')}</h2><button onClick={reload}>{t('refresh')}</button></div><div className="history">{s.jobs?.map((x:Row)=><button key={x.id}><span><b>{x.ticket?.ticketNumber}</b><small>{x.printer?.name}</small></span><span><b>{statusLabel(x.status,language)}</b><small>{t('attempts')} {x.attempts}/{x.maxAttempts}</small></span></button>)}</div></section></>}

function secureNumber(max:number){const value=new Uint32Array(1);crypto.getRandomValues(value);return value[0]%(max+1)}
function HaitianSell({state:s,lines,setLines,gameForDraw,submit,online}:any){
 const[draw,setDraw]=useState(s.draws?.[0]?.id??''),[maryaj,setMaryaj]=useState(''),[stake,setStake]=useState('');
 useEffect(()=>{if(!draw&&s.draws?.[0])setDraw(s.draws[0].id)},[s.draws,draw]);
 const game=gameForDraw(draw),bets=game?.betTypes?.filter((x:Row)=>x.active!==false).map((x:Row)=>x.betType)??[];
 function addMaryaj(){const bet=bets.find((x:Row)=>x.code==='MARYAJ'),numbers=[...new Set(maryaj.split(/[^0-9]+/).filter(value=>/^\d{1,2}$/.test(value)).map(value=>value.padStart(2,'0')))];if(!bet||numbers.length<2||!Number(stake))return;const generated:BetLine[]=[];for(let i=0;i<numbers.length;i++)for(let j=i+1;j<numbers.length;j++)generated.push({betTypeId:bet.id,selection:`${numbers[i]} ${numbers[j]}`,stake});setLines([...lines.filter((x:BetLine)=>x.betTypeId||x.selection||x.stake),...generated])}
 function addAutoLoto(){const bet=bets.find((x:Row)=>x.code==='LOTO4');if(!bet||!Number(stake))return;setLines([...lines.filter((x:BetLine)=>x.betTypeId||x.selection||x.stake),{betTypeId:bet.id,selection:String(secureNumber(9999)).padStart(4,'0'),stake}])}
 function addBoulPe(){const bet=bets.find((x:Row)=>x.code==='BOUL_PE');if(!bet||!Number(stake))return;const pairs=['00','11','22','33','44','55','66','77','88','99'].map(selection=>({betTypeId:bet.id,selection,stake}));setLines([...lines.filter((x:BetLine)=>x.betTypeId||x.selection||x.stake),...pairs])}
 return <section className="panel sell"><h2>New Ticket</h2><form onSubmit={submit}><div className="form-grid"><label>Open draw<select name="drawId" value={draw} onChange={e=>setDraw(e.target.value)} required><option value="">Select draw</option>{s.draws?.map((x:Row)=><option value={x.id} key={x.id}>{x.game?.name??x.drawNumber} — {x.drawNumber}</option>)}</select></label><label>Printer<select name="printerId"><option value="">No auto-print</option>{s.printers?.map((x:Row)=><option key={x.id} value={x.id}>{x.name} ({x.status})</option>)}</select></label><label>Ticket template<select name="templateId"><option value="">Select</option>{s.templates?.filter((x:Row)=>x.kind==='TICKET').map((x:Row)=><option key={x.id} value={x.id}>{x.name} v{x.version}</option>)}</select></label></div><section className="panel"><h3>Jwèt otomatik</h3><div className="form-grid"><label>Nimewo pou Maryaj<input value={maryaj} placeholder="12 25 48" onChange={e=>setMaryaj(e.target.value)}/></label><label>Montan pa liy<input value={stake} type="number" min=".01" step=".01" onChange={e=>setStake(e.target.value)}/></label><div className="buttons"><button type="button" onClick={addMaryaj}>Jenere Maryaj</button><button type="button" onClick={addAutoLoto}>Loto 4 otomatik</button><button type="button" onClick={addBoulPe}>Boul Pè otomatik</button></div></div><small>Loto 3 ak Loto 5 rete manyèl.</small></section>{lines.map((line:BetLine,i:number)=><div className="bet-line" key={i}><label>Bet type<select value={line.betTypeId} onChange={e=>setLines(lines.map((x:BetLine,j:number)=>j===i?{...x,betTypeId:e.target.value}:x))} required><option value="">Select</option>{bets.map((x:Row)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Numbers<input value={line.selection} inputMode="numeric" onChange={e=>setLines(lines.map((x:BetLine,j:number)=>j===i?{...x,selection:e.target.value}:x))} required/></label><label>Stake<input value={line.stake} type="number" min=".01" step=".01" onChange={e=>setLines(lines.map((x:BetLine,j:number)=>j===i?{...x,stake:e.target.value}:x))} required/></label><button type="button" className="danger" onClick={()=>setLines(lines.filter((_:BetLine,j:number)=>j!==i))}>×</button></div>)}<div className="ticket-actions"><button type="button" className="secondary" onClick={()=>setLines([...lines,{betTypeId:'',selection:'',stake:''}])}>+ Add bet</button><b>Total: {cash(lines.reduce((n:number,x:BetLine)=>n+Number(x.stake||0),0))}</b><button disabled={!online}>VALIDATE & SELL</button></div></form></section>
}

function HaitianPos({state:s,lines,setLines,gameForDraw,submit,online}:any){
 const{t,language}=useMerchantLanguage();
 const[draw,setDraw]=useState(s.draws?.[0]?.id??''),[number,setNumber]=useState(''),[entryStake,setEntryStake]=useState(''),[allStake,setAllStake]=useState(''),[lotoStake,setLotoStake]=useState(''),[maryajNumber,setMaryajNumber]=useState(''),[maryajStake,setMaryajStake]=useState(''),[positions,setPositions]=useState<number[]>([1]),[autoDialog,setAutoDialog]=useState<'maryaj'|'loto'|null>(null);
 useEffect(()=>{if(!draw&&s.draws?.[0])setDraw(s.draws[0].id)},[s.draws,draw]);
 const game=gameForDraw(draw),bets=game?.betTypes?.filter((x:Row)=>x.active!==false).map((x:Row)=>x.betType)??[];
 const codeFor=(length:number)=>({2:'BOLET',3:'LOTO3',4:'LOTO4',5:'LOTO5'}as Record<number,string>)[length];
 const bolet:string[]=[...new Set<string>((lines as BetLine[]).filter((x:BetLine)=>x.betTypeId===bets.find((bet:Row)=>bet.code==='BOLET')?.id&&/^\d{2}$/.test(x.selection)).map((x:BetLine)=>x.selection.padStart(2,'0')))];
 function add(){const clean=number.replace(/\D/g,'');if(clean.length<2||clean.length>5||!(Number(entryStake)>0))return;const bet=bets.find((x:Row)=>x.code===codeFor(clean.length));if(!bet)return;const next=positions.map(resultPosition=>({betTypeId:bet.id,betName:bet.name,selection:clean,stake:entryStake,resultPosition}));setLines([...lines,...next]);setNumber('');setEntryStake('')}
 function addMaryaj(){const bet=bets.find((x:Row)=>x.code==='MARYAJ');if(!bet||bolet.length<2||!(Number(allStake)>0))return;const generated:BetLine[]=[];for(let first=0;first<bolet.length;first++)for(let second=first+1;second<bolet.length;second++)generated.push({betTypeId:bet.id,betName:bet.name,selection:`${bolet[first]} ${bolet[second]}`,stake:allStake});setLines([...lines,...generated]);setAutoDialog(null)}
 function addNormalMaryaj(){const parts=maryajNumber.trim().split(/\s*[xX×-]\s*/);const bet=bets.find((x:Row)=>x.code==='MARYAJ');if(!bet||parts.length!==2||parts.some(part=>!/^\d{2}$/.test(part))||!(Number(maryajStake)>0))return;setLines([...lines,{betTypeId:bet.id,betName:bet.name,selection:`${parts[0]} ${parts[1]}`,stake:maryajStake}]);setMaryajNumber('');setMaryajStake('')}
 function addBoulPe(){const bet=bets.find((x:Row)=>x.code==='BOUL_PE');if(!bet||!(Number(allStake)>0))return;setLines([...lines,...['00','11','22','33','44','55','66','77','88','99'].map(selection=>({betTypeId:bet.id,betName:bet.name,selection,stake:allStake}))])}
 function addAutoLoto4(){const bet=bets.find((x:Row)=>x.code==='LOTO4');if(!bet||bolet.length<2||!(Number(lotoStake)>0))return;const generated:BetLine[]=[];for(let first=0;first<bolet.length;first++)for(let second=first+1;second<bolet.length;second++)for(const selection of [`${bolet[first]}${bolet[second]}`,`${bolet[second]}${bolet[first]}`])for(const resultPosition of positions)generated.push({betTypeId:bet.id,betName:bet.name,selection,stake:lotoStake,resultPosition});setLines([...lines,...generated]);setAutoDialog(null)}
 function applyAll(){if(Number(allStake)>0)setLines(lines.map((line:BetLine)=>({...line,stake:allStake})))}
 const total=lines.reduce((sum:number,line:BetLine)=>sum+Number(line.stake||0),0);
 return <section className="panel sell"><div className="sell-heading"><div><span className="eyebrow">{t('sellDesk')}</span><h2>{t('sell')}</h2><p>{t('sellHelp')}</p></div><strong className="sale-total">{t('total')}<span>{cash(total)}</span></strong></div><form onSubmit={submit}>
  <div className="sell-draw-grid"><label>{t('openDraw')}<select name="drawId" value={draw} onChange={e=>{setDraw(e.target.value);setLines([])}} required><option value="">{t('choose')}</option>{s.draws?.map((x:Row)=><option value={x.id} key={x.id}>{drawLabel(x,language)}</option>)}</select></label><label>{t('printer')}<select name="printerId"><option value="">{t('autoPrint')}</option>{s.printers?.map((x:Row)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>{t('template')}<select name="templateId"><option value="">{t('choose')}</option>{s.templates?.filter((x:Row)=>x.kind==='TICKET').map((x:Row)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div>
  <section className="sell-entry"><div className="form-grid"><label>{t('ball')}<input value={number} inputMode="numeric" maxLength={5} autoFocus placeholder="12, 123, 1234, 12345" onChange={e=>setNumber(e.target.value.replace(/\D/g,''))}/></label><label>{t('ballPrice')}<input value={entryStake} type="number" min=".01" step=".01" onChange={e=>setEntryStake(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();add()}}}/></label><button type="button" onClick={add}>{t('addBall')}</button></div>
   <div className="sell-options"><div><b>{t('position')}</b><div className="buttons">{[1,2,3].map(position=><button type="button" className={positions.length===1&&positions[0]===position?'active':'secondary'} onClick={()=>setPositions([position])} key={position}>{position===1?t('firstPosition'):`${position}${t('positionSuffix')}`}</button>)}<button type="button" className={positions.length===3?'active':'secondary'} onClick={()=>setPositions([1,2,3])}>{t('allOptions')}</button></div></div><small>{t('selectionHelp')}</small></div>
  </section>
  <div className="auto-tools"><div className="auto-tools-title"><div><h3>{t('autoTools')}</h3><small>{t('boletCount').replace('{count}',String(bolet.length))}</small></div><div className="buttons"><button type="button" onClick={()=>setAutoDialog('maryaj')} disabled={bolet.length<2||!bets.some((x:Row)=>x.code==='MARYAJ')}>{t('marriage')}</button><button type="button" onClick={()=>setAutoDialog('loto')} disabled={bolet.length<2||!bets.some((x:Row)=>x.code==='LOTO4')}>{t('autoLoto')}</button><button type="button" className="secondary" onClick={addBoulPe} disabled={!bets.some((x:Row)=>x.code==='BOUL_PE')}>{t('pair')}</button></div></div>
   <div className="form-grid stake-tools"><label>{t('allPrice')}<input value={allStake} type="number" min=".01" step=".01" onChange={e=>setAllStake(e.target.value)} placeholder="0.00"/></label><button type="button" className="secondary" onClick={applyAll} disabled={!lines.length}>{t('applyPrice')}</button><small>{t('autoHelp')}</small></div>
  </div>
  <details className="manual-maryaj"><summary>{t('manualMaryaj')}</summary><div className="form-grid"><label>{t('twoNumbers')}<input value={maryajNumber} onChange={e=>setMaryajNumber(e.target.value)} placeholder="15x25" inputMode="numeric"/></label><label>{t('price')}<input value={maryajStake} onChange={e=>setMaryajStake(e.target.value)} type="number" min=".01" step=".01"/></label><button type="button" onClick={addNormalMaryaj}>{t('addManualMaryaj')}</button></div></details>
  {lines.map((line:BetLine,index:number)=><div className="bet-line" key={`${line.selection}-${line.resultPosition}-${index}`}><b>{line.selection}</b><span>{line.betName}{line.resultPosition?` · ${t('option')} ${line.resultPosition}`:''}</span><label>{t('price')}<input value={line.stake} type="number" min=".01" step=".01" onChange={e=>setLines(lines.map((x:BetLine,i:number)=>i===index?{...x,stake:e.target.value}:x))}/></label><button type="button" className="danger" aria-label={t('removeLine')} onClick={()=>setLines(lines.filter((_:BetLine,i:number)=>i!==index))}>×</button></div>)}
  <div className="ticket-actions"><b>{t('lineCount').replace('{count}',String(lines.length))} · {t('total')}: {cash(total)}</b><button disabled={!online||!draw||!lines.length}>{t('validate')}</button></div></form>
  {autoDialog&&<div className="dialog-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setAutoDialog(null)}}><section className="auto-dialog" role="dialog" aria-modal="true" aria-labelledby="auto-dialog-title"><button type="button" className="dialog-close secondary" aria-label={t('close')} onClick={()=>setAutoDialog(null)}>×</button><span className="eyebrow">{t('autoTools')}</span><h3 id="auto-dialog-title">{autoDialog==='maryaj'?t('maryajDialogTitle'):t('lotoDialogTitle')}</h3><p>{autoDialog==='maryaj'?t('maryajDialogHelp'):t('lotoDialogHelp')}</p><div className="bolet-chips">{bolet.map(value=><span key={value}>{value}</span>)}</div>{autoDialog==='loto'&&<div className="dialog-positions"><b>{t('position')}</b><div className="buttons">{[1,2,3].map(position=><button type="button" key={position} className={positions.includes(position)?'active':'secondary'} onClick={()=>setPositions(positions.includes(position)?positions.filter(x=>x!==position):[...positions,position].sort())}>{position===1?t('firstPosition'):`${position}${t('positionSuffix')}`}</button>)}<button type="button" className={positions.length===3?'active':'secondary'} onClick={()=>setPositions([1,2,3])}>{t('allOptions')}</button></div></div>}<label>{t('linePrice')}<input autoFocus value={autoDialog==='maryaj'?allStake:lotoStake} type="number" min=".01" step=".01" onChange={e=>autoDialog==='maryaj'?setAllStake(e.target.value):setLotoStake(e.target.value)}/></label><small>{t('editableLines')}</small><div className="buttons dialog-actions"><button type="button" className="secondary" onClick={()=>setAutoDialog(null)}>{t('cancelDialog')}</button><button type="button" onClick={autoDialog==='maryaj'?addMaryaj:addAutoLoto4} disabled={bolet.length<2||!(Number(autoDialog==='maryaj'?allStake:lotoStake)>0)||!positions.length}>{t('generate')}</button></div></section></div>}
 </section>
}
function LiveResults({request}:{request:(path:string)=>Promise<any>}){const{t,language}=useMerchantLanguage();const[rows,setRows]=useState<Row[]>([]),[error,setError]=useState('');useEffect(()=>{let active=true;const load=async()=>{try{const draws=await request('/lottery/draws');if(active){setRows(draws.filter((x:Row)=>x.status==='RESULT_PUBLISHED'));setError('')}}catch(e){if(active)setError(e instanceof Error?e.message:String(e))}};void load();const timer=setInterval(load,15000);return()=>{active=false;clearInterval(timer)}},[request]);return <section className="panel"><div className="title"><div><h2>{t('live')}</h2><small>{t('updates')}</small></div></div>{error&&<p className="message">{error}</p>}<div className="stats">{rows.map(row=><article key={row.id}>{row.game?.logoUrl&&<img src={row.game.logoUrl} alt={row.game?.name} style={{height:48,maxWidth:120,objectFit:'contain'}}/>}<span>{row.game?.name} · {row.drawNumber}</span><strong>{row.result?.winningKeys?.join(' · ')??'—'}</strong></article>)}</div>{!rows.length&&!error&&<p>{t('noResults')}</p>}</section>}
