'use client';
import{FormEvent,useCallback,useEffect,useMemo,useState}from'react';import'./styles.css';
import PrintReceipt from './print-receipt';
import MerchantReports from './merchant-reports';
import ManualMaryajDialog from './manual-maryaj-dialog';
import FreeMaryajDialog from './free-maryaj-dialog';
import {useMerchantLanguage,statusLabel} from './language-switcher';
import {drawLabel} from './draw-label';
import {buildAutomaticBoulPe,buildAutomaticLoto4,buildAutomaticMaryaj,collectAutomaticNumbers} from './sell-tools';
const API=process.env.NEXT_PUBLIC_API_URL??'http://localhost:4000/api/v1';const RESET_URL=process.env.NEXT_PUBLIC_PASSWORD_RESET_URL??'https://lottivexa-public-site.onrender.com/reset-password';type Row=Record<string,any>;type Screen='dashboard'|'sell'|'check'|'history'|'reports'|'results'|'cash'|'printer'|'more';type BetLine={betTypeId:string;selection:string;stake:string;resultPosition?:number;betName?:string};
function form(e:HTMLFormElement){return Object.fromEntries(new FormData(e))as Row}function id(){return crypto.randomUUID()}function cash(v:any){return new Intl.NumberFormat(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v??0))}function currencyMark(_value:string){return '$'}function jwt(t:string){try{return JSON.parse(atob(t.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')))}catch{return{permissions:[]}}}
export default function MerchantPos(){const{t,language}=useMerchantLanguage();const[token,setToken]=useState(''),[refresh,setRefresh]=useState(''),[force,setForce]=useState(false),[screen,setScreen]=useState<Screen>('dashboard'),[state,setState]=useState<Row>({}),[selected,setSelected]=useState<Row|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[online,setOnline]=useState(true),[lines,setLines]=useState<BetLine[]>([]),[pendingBonus,setPendingBonus]=useState<Row|null>(null);const permissions=useMemo<string[]>(()=>jwt(token).permissions??[],[token]),can=(p:string)=>permissions.includes(p);
 useEffect(()=>{setToken(localStorage.getItem('merchant_access')??'');setRefresh(localStorage.getItem('merchant_refresh')??'');setForce(localStorage.getItem('merchant_force')==='true');const status=()=>setOnline(navigator.onLine);status();addEventListener('online',status);addEventListener('offline',status);return()=>{removeEventListener('online',status);removeEventListener('offline',status)}},[]);
 const logout=useCallback(()=>{for(const k of['merchant_access','merchant_refresh','merchant_force'])localStorage.removeItem(k);setToken('');setRefresh('');setState({});setSelected(null)},[]);
 const request=useCallback(async(path:string,init:RequestInit={})=>{let access=localStorage.getItem('merchant_access')??token;const send=()=>fetch(`${API}${path}`,{...init,headers:{'content-type':'application/json',authorization:`Bearer ${access}`,...init.headers}});let r=await send();if(r.status===401&&refresh){const renewed=await fetch(`${API}/auth/refresh`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({refreshToken:refresh})});if(renewed.ok){const n=await renewed.json();access=n.accessToken;localStorage.setItem('merchant_access',n.accessToken);localStorage.setItem('merchant_refresh',n.refreshToken);setToken(n.accessToken);setRefresh(n.refreshToken);r=await send()}else logout()}const body=path.startsWith('/reports/sales.pdf')?await r.blob():await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.code??body.message??`HTTP_${r.status}`);return body},[token,refresh,logout]);
 const run=useCallback(async(fn:()=>Promise<any>,ok?:string)=>{setBusy(true);setMessage('');try{const result=await fn();if(ok)setMessage(ok);return result}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}},[]);
 const load=useCallback(async()=>{const result=await run(async()=>{const[d,g,p,t,j,c]=await Promise.all([request('/merchants/me/dashboard'),request('/lottery/games'),can('printers.view')?request('/printing/printers'):[],can('printers.view')?request('/printing/templates'):[],can('printers.view')?request('/printing/jobs'):[],can('finance.view')?request('/cash/session/current'):null]);return{dashboard:d,games:g,draws:(await request('/lottery/draws')).filter((x:Row)=>x.status==='OPEN'),printers:p,templates:t,jobs:j,session:c}});if(result)setState(result)},[request,run,permissions.join('|')]);
 useEffect(()=>{if(!token||force)return;void load();const timer=setInterval(()=>void load(),60000);return()=>clearInterval(timer)},[token,force,load]);
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();const result=await run(async()=>{const r=await fetch(`${API}/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form(e.currentTarget))}),body=await r.json();if(!r.ok){const code=body?.error?.code??body?.code??body?.message??'INVALID_CREDENTIALS';throw new Error(code==='ACCOUNT_DISABLED_CONTACT_ADMIN'?'Kont machann sa a dezaktive. Kontakte administratè tenant la.':code)}return body},'Koneksyon reyisi.');if(result){localStorage.setItem('merchant_access',result.accessToken);localStorage.setItem('merchant_refresh',result.refreshToken);localStorage.setItem('merchant_force',String(result.forcePasswordChange));setToken(result.accessToken);setRefresh(result.refreshToken);setForce(result.forcePasswordChange)}}
 async function mutate(path:string,body:Row,ok:string){const result=await run(()=>request(path,{method:'POST',body:JSON.stringify(body)}),ok);if(result)await load();return result}
 const gameForDraw=(drawId:string)=>{const draw=state.draws?.find((x:Row)=>x.id===drawId);return state.games?.find((x:Row)=>x.id===draw?.gameId)};
  async function sell(e:FormEvent<HTMLFormElement>|null,freeMaryaj:{selection:string[]}[]=[],savedMeta?:Row){e?.preventDefault();const meta=savedMeta??(e?form(e.currentTarget):{}),payload={drawId:meta.drawId,deviceId:meta.deviceId||undefined,idempotencyKey:id(),lines:lines.map(x=>({betTypeId:x.betTypeId,selection:x.selection.split(/[ ,.-]+/).filter(Boolean),stake:x.stake,resultPosition:x.resultPosition})),...(freeMaryaj.length?{freeMaryaj}:{})};const ticket=await mutate('/tickets',payload,'Tikè kreye epi sove.');if(ticket){let detail=ticket;try{detail=await request(`/tickets/${encodeURIComponent(ticket.ticketNumber)}`)}catch{}setSelected(detail);setLines([]);if(meta.printerId&&meta.templateId)await mutate('/printing/jobs',{ticketId:ticket.id,printerId:meta.printerId,templateId:meta.templateId,idempotencyKey:`print:${ticket.id}:${id()}`},'Tikè kreye; print job antre nan queue.');setScreen('check')}}
 async function lookup(e:FormEvent<HTMLFormElement>){e.preventDefault();const ref=String(form(e.currentTarget).reference),ticket=await run(()=>request(`/tickets/${encodeURIComponent(ref)}`));if(ticket)setSelected(ticket)}
 async function lookupTicket(reference:string){const ticket=await run(()=>request(`/tickets/${encodeURIComponent(reference)}`));if(ticket){setSelected(ticket);setScreen('check')}}
 async function pay(){if(selected)await mutate('/payouts',{ticketReference:selected.ticketNumber,idempotencyKey:id()},'Payout otorize; ledger ajiste.').then(async r=>{if(r)setSelected(await request(`/tickets/${selected.ticketNumber}`))})}
 async function cancel(){if(selected)await mutate(`/tickets/${encodeURIComponent(selected.ticketNumber)}/cancel`,{},'Ticket anile; sale ak commission ranvèse.').then(r=>r&&setSelected(r))}
 async function printTicket(){if(!selected)return;try{const ticket=await request(`/tickets/${encodeURIComponent(selected.ticketNumber)}`);setSelected(ticket);requestAnimationFrame(()=>requestAnimationFrame(()=>{const receipt=document.querySelector('.print-receipt');let style:HTMLStyleElement|undefined;if(receipt){const clone=receipt.cloneNode(true) as HTMLElement;clone.style.cssText='display:block;position:absolute;left:-10000px;top:0;width:58mm;max-width:58mm;visibility:hidden';document.body.append(clone);const height=Math.max(65,Math.ceil(clone.scrollHeight*25.4/96+8));clone.remove();style=document.createElement('style');style.textContent=`@page{size:58mm ${height}mm;margin:0}`;document.head.append(style);window.addEventListener('afterprint',()=>style?.remove(),{once:true})}window.print()}));}catch(e){setMessage(e instanceof Error?e.message:String(e))}}
 if(!token)return <main className="login"><h1>LOTTIVEXA</h1><h2>{t('login')}</h2><p>{t('intro')}</p><form onSubmit={login}><label>{t('tenant')}<input name="tenant" required/></label><label>{t('username')}<input name="username" required/></label><label>{t('password')}<input name="password" type="password" minLength={8} required/></label><button disabled={busy}>{t('submit')}</button></form><a href={RESET_URL}>{t('forgot')}</a>{message&&<p className="message">{message}</p>}</main>;
 if(force)return <main className="login"><h1>{t('forcePassword')}</h1><form onSubmit={async e=>{e.preventDefault();const result=await mutate('/users/me/change-password',form(e.currentTarget),'Modpas chanje. Konekte ankò.');if(result)setTimeout(logout,700)}}><label>{t('currentPassword')}<input name="currentPassword" type="password" required/></label><label>{t('newPassword')}<input name="newPassword" type="password" minLength={12} required/></label><button>{t('changePassword')}</button></form><button className="secondary" onClick={logout}>{t('back')}</button>{message&&<p className="message">{message}</p>}</main>;
 function replayTicket(ticket:Row){setLines((ticket.lines??[]).map((line:Row)=>{const parts=String(line.selectionKey).split('@');return{betTypeId:line.betTypeId,selection:parts[0],stake:String(line.stake),resultPosition:Number(parts[1]||1),betName:line.betType?.name}}));setMessage("Tikè a kopye. Chwazi yon tiraj ki ouvè epi valide nouvo tikè a.");setScreen("sell")}
  const nav:[Screen,string][]=[['dashboard',t('dashboard')],['sell',t('sell')],['check',t('check')],['history',t('history')],['reports',t('reports')],['results',t('results')],['cash',t('cash')],['printer',t('printer')]],mobileNav:[Screen,string][]=[['dashboard',t('dashboard')],['sell',t('sell')],['history',t('history')],['reports',t('reports')],['more',t('more')]];
  return <div className="pos"><header><div><b>{state.dashboard?.businessName??'Bolet'}</b><small>{state.dashboard?.merchant?.displayName??'Merchant'} · {state.dashboard?.merchant?.branch?.name??''}</small></div><div className={online?'online':'offline'}>● {online?t('online'):t('offline')}</div><button className="secondary" onClick={logout}>{t('logout')}</button></header><nav><div className="nav-desktop">{nav.map(x=><button className={screen===x[0]?'active':''} key={x[0]} onClick={()=>setScreen(x[0])}>{x[1]}</button>)}</div><div className="nav-mobile">{mobileNav.map(x=><button className={screen===x[0]?'active':''} key={x[0]} onClick={()=>setScreen(x[0])}>{x[1]}</button>)}</div></nav><main>{message&&<p className="message">{message}</p>}{busy&&<div className="busy">{t('loading')}</div>}{screen==='dashboard'&&<Dashboard state={state} reload={load} onNavigate={setScreen} selectTicket={(x:Row)=>{void lookupTicket(x.ticketNumber)}}/>} {screen==='sell'&&<HaitianPos state={state} lines={lines} setLines={setLines} gameForDraw={gameForDraw} submit={sell} online={online} openBonus={setPendingBonus}/>} {screen==='check'&&<Check selected={selected} lookup={lookup} pay={pay} cancel={cancel} printTicket={printTicket} replay={replayTicket} can={can}/>} {screen==='history'&&<History rows={state.dashboard?.recent??[]} select={(x:Row)=>{void lookupTicket(x.ticketNumber)}}/>} {screen==='reports'&&<MerchantReports request={request}/>} {screen==='results'&&<LiveResults request={request}/>} {screen==='cash'&&<Cash session={state.session} mutate={mutate} can={can}/>} {screen==='printer'&&<Printer state={state} reload={load}/>} {screen==='more'&&<More onNavigate={setScreen}/>}</main><PrintReceipt ticket={selected} businessName={state.dashboard?.businessName??'Bolet'} branchName={state.dashboard?.merchant?.branch?.name} currency={state.dashboard?.currency??'USD'}/>{pendingBonus&&<FreeMaryajDialog language={language} onClose={()=>setPendingBonus(null)} onAdd={freeMaryaj=>{const meta=pendingBonus;setPendingBonus(null);void sell(null,freeMaryaj,meta)}}/>}</div>
 }

function Dashboard({state:s,reload,onNavigate,selectTicket}:any){
 const{t,language}=useMerchantLanguage(),d=s.dashboard??{},currency=d.currency??'USD';
 const date=d.businessDate?new Date(d.businessDate+'T12:00:00-04:00').toLocaleDateString(language==='fr'?'fr-FR':'fr-HT',{timeZone:'America/Port-au-Prince',weekday:'long',day:'2-digit',month:'long',year:'numeric'}):'';
 const draws=(s.draws??[]).slice(0,4);
 return <div className="merchant-dashboard">
  <section className="dashboard-welcome"><div className="welcome-mark">☀</div><div><span>{t('welcome')} {d.merchant?.displayName??''}</span><small>{t('activeAsOf')} {date}</small></div><button className="secondary" onClick={reload}>{t('reload')}</button></section>
  <div className="dashboard-kpis">
   <article className="sales"><span>▤ {t('sales')}</span><strong>{currencyMark(currency)}{cash(d.sales)}</strong><small>{t('today')}</small></article>
   <article className="tickets"><span>◇ {t('tickets')}</span><strong>{d.ticketCount??0}</strong><small>{t('today')}</small></article>
   <article className="payouts"><span>♜ {t('payouts')}</span><strong>{currencyMark(currency)}{cash(d.payouts)}</strong><small>{d.payoutCount??0} {t('winnersPaid')}</small></article>
   <article className="commission"><span>% {t('commission')}</span><strong>{currencyMark(currency)}{cash(d.commission)}</strong><small>{t('shift')}: {d.session?t('open'):t('closed')}</small></article>
  </div>
  <section className="dashboard-actions">
   <button className="action-sell" onClick={()=>onNavigate('sell')}><b>＋</b><span>{t('sell')}<small>{t('quickSellHint')}</small></span></button>
   <button onClick={()=>onNavigate('check')}><b>⌕</b><span>{t('check')}<small>{t('quickCheckHint')}</small></span></button>
   <button onClick={()=>onNavigate('results')}><b>▥</b><span>{t('results')}<small>{t('quickResultsHint')}</small></span></button>
  </section>
  <div className="dashboard-lists">
   <section className="panel"><div className="title"><h2>{t('recent')}</h2><button className="text-button" onClick={()=>onNavigate('history')}>{t('seeAll')}</button></div><History rows={d.recent??[]} select={selectTicket}/></section>
   <section className="panel"><div className="title"><h2>{t('upcomingDraws')}</h2><button className="text-button" onClick={()=>onNavigate('sell')}>{t('sell')}</button></div><div className="upcoming-draws">{draws.length?draws.map((row:Row)=><article key={row.id}><span className="draw-mark">◉</span><div><b>{drawLabel(row,language)}</b><small>{row.game?.name??t('lottery')}</small></div><span className="draw-open">{t('open')}</span></article>):<p className="empty">{t('noOpenDraws')}</p>}</div></section>
  </div>
 </div>
}
function More({onNavigate}:{onNavigate:(screen:Screen)=>void}){const{t}=useMerchantLanguage();return <section className="panel more-menu"><span className="eyebrow">{t('more')}</span><h2>{t('moreTools')}</h2><div>{([['check',t('check')],['results',t('results')],['cash',t('cash')],['printer',t('printer')]] as [Screen,string][]).map(([screen,label])=><button key={screen} onClick={()=>onNavigate(screen)}>{label}<span>›</span></button>)}</div></section>}
function Check({selected:t,lookup,pay,cancel,printTicket,replay,can}:any){
 const{t:tr,language}=useMerchantLanguage();
 const verified=t?.status==='WINNER'&&Number(t?.winning?.winningAmount)>0&&(t?.lines??[]).some((line:Row)=>line.isWinner===true);
 const currency=t?.currency??'USD';
 return <>
  <section className="panel">
   <h2>{tr('ticketCheck')}</h2>
   <form className="lookup" onSubmit={lookup}><input name="reference" placeholder={tr('ticketNumber')} autoFocus required/><button>{tr('search')}</button></form>
  </section>
  {t&&<section className="ticket">
   <div className="ticket-head"><h2>{t.ticketNumber}</h2><b className={String(t.status).toLowerCase()}>{t.status==='WINNER'&&!verified?(language==='fr'?'Vérification requise':'Bezwen verifikasyon'):statusLabel(t.status,language)}</b></div>
   <p>{t.draw?drawLabel(t.draw,language):t.game?.name}</p>
   {(t.lines??[]).map((line:Row)=>{
    const parts=String(line.selectionKey??'').split('@'),count=Number(line.winCount??0),base=Number(line.potentialWin??0),win=base*(count>0?count:1);
    return <div className="ticket-line" key={line.id}>
     <div className="ticket-selection"><small>{line.betType?.name??'Bolet'}{line.isPromotional?' · '+(language==='fr'?'GRATUIT':'GRATIS'):''}</small><b>{parts[0].replaceAll('-',' × ')}</b>{parts[1]&&<strong className="ticket-position-display">OP {parts[1]}</strong>}{count>1&&<small className="receipt-dekabes">DEKABÈS × {count}</small>}</div>
     <span>{line.isPromotional?(language==='fr'?'GRATUIT':'GRATIS'):`${currencyMark(currency)}${cash(line.stake)}`} → ${cash(win)}</span>
    </div>;
   })}
   <div className="total"><span>{tr('amount')} <b>{currencyMark(currency)}{cash(t.amount)}</b></span><span>{tr('potential')} <b>{currencyMark(currency)}{cash(t.potentialWin)}</b></span></div>
   {verified&&<p className="winner">{language==='fr'?'Gain confirmé':'Gany konfime'}: {currencyMark(currency)}{cash(t.winning.winningAmount)}</p>}
   <div className="buttons">{can('tickets.pay')&&verified&&!t.payout&&<button onClick={pay}>{tr('pay')}</button>}{can('tickets.cancel')&&t.status==='VALID'&&<button className="danger" onClick={cancel}>{tr('cancel')}</button>}<button className="secondary" onClick={()=>replay(t)}>{tr('copy')}</button>{can('tickets.reprint')&&<button className="secondary" onClick={printTicket}>{tr('print')}</button>}</div>
  </section>}
 </>;
}
function History({rows,select}:{rows:Row[];select:(x:Row)=>void}){const{t,language}=useMerchantLanguage();return <div className="history">{rows.length?rows.map(x=><button key={x.id} onClick={()=>select(x)}><span><b>{x.ticketNumber}</b><small>{new Date(x.createdAt).toLocaleString()}</small></span><span><b>${cash(x.amount)}</b><small>{x.status==='WINNER'&&(!(Number(x.winning?.winningAmount)>0)||!(x.lines??[]).some((line:Row)=>line.isWinner===true))?(language==='fr'?'À vérifier':'Pou verifye'):statusLabel(x.status,language)}</small></span></button>):<p>{t('none')}</p>}</div>}
function Cash({session,mutate,can}:any){const{t,language}=useMerchantLanguage();if(!can('finance.view'))return <section className="panel"><h2>{t('cash')}</h2><p>{t('permissionCash')}</p></section>;return <section className="panel"><h2>{t('cash')}</h2>{session?<><div className="stats"><article><span>{t('status')}</span><strong>{statusLabel(session.status,language)}</strong></article><article><span>{t('opening')}</span><strong>${cash(session.openingCash)}</strong></article><article><span>{t('movements')}</span><strong>{session.movements?.length??0}</strong></article></div>{can('finance.adjust')&&<form className="form-grid" onSubmit={e=>{e.preventDefault();const x=form(e.currentTarget);void mutate(`/cash/session/${session.id}/movements`,{...x,idempotencyKey:id()},'Cash movement saved.');e.currentTarget.reset()}}><label>{t('type')}<select name="type"><option>CASH_IN</option><option>CASH_OUT</option><option>EXPENSE</option><option>DEPOSIT</option><option>WITHDRAWAL</option><option>ADJUSTMENT</option></select></label><label>{t('amount')}<input name="amount" type="number" min=".01" step=".01" required/></label><label>{t('reason')}<input name="reason" required/></label><button>{t('addMovement')}</button></form>}<form className="lookup" onSubmit={e=>{e.preventDefault();void mutate(`/cash/session/${session.id}/close`,form(e.currentTarget),'Shift closed; final difference calculated.')}}><input name="actualCash" type="number" step=".01" min="0" placeholder={t("actualCash")} required/><button className="danger">{t('closeShift')}</button></form></>:<form className="lookup" onSubmit={e=>{e.preventDefault();void mutate('/cash/session/open',form(e.currentTarget),'Shift opened.')}}><input name="openingCash" type="number" min="0" step=".01" placeholder="Opening cash" required/><button>{t('openShift')}</button></form>}</section>}
function Printer({state:s,reload}:any){const{t,language}=useMerchantLanguage();return <><div className="stats">{s.printers?.map((x:Row)=><article key={x.id}><span>{x.connectionType}</span><strong>{x.name}</strong><small>{statusLabel(x.status,language)}{x.isDefault?' · DEFAULT':''}</small></article>)}</div><section className="panel"><div className="title"><h2>{t('printerQueue')}</h2><button onClick={reload}>{t('refresh')}</button></div><div className="history">{s.jobs?.map((x:Row)=><button key={x.id}><span><b>{x.ticket?.ticketNumber}</b><small>{x.printer?.name}</small></span><span><b>{statusLabel(x.status,language)}</b><small>{t('attempts')} {x.attempts}/{x.maxAttempts}</small></span></button>)}</div></section></>}

function HaitianPos({state:s,lines,setLines,gameForDraw,submit,online,openBonus}:any){
 const{t,language}=useMerchantLanguage();
 const[draw,setDraw]=useState(s.draws?.[0]?.id??''),[number,setNumber]=useState(''),[entryStake,setEntryStake]=useState(''),[lotoStake,setLotoStake]=useState(''),[maryajAutoStake,setMaryajAutoStake]=useState(''),[boulPeStake,setBoulPeStake]=useState(''),[positions,setPositions]=useState<number[]>([1]),[toolMenuOpen,setToolMenuOpen]=useState(false),[autoDialog,setAutoDialog]=useState<'maryaj'|'loto'|'boulPe'|null>(null),[manualOpen,setManualOpen]=useState(false),[saleError,setSaleError]=useState('');
 useEffect(()=>{if(!draw&&s.draws?.[0])setDraw(s.draws[0].id)},[s.draws,draw]);
 const game=gameForDraw(draw),bets=game?.betTypes?.filter((x:Row)=>x.active!==false).map((x:Row)=>x.betType)??[];
 const codeFor=(length:number)=>({2:'BOLET',3:'LOTO3',4:'LOTO4',5:'LOTO5'}as Record<number,string>)[length];
 const bolet=collectAutomaticNumbers(lines as BetLine[],bets as {id:string;code:string;name:string}[]);
 const boulPeNumbers=['00','11','22','33','44','55','66','77','88','99'];
 function freeMaryaj(){const values=[...bolet];for(const line of lines){const code=bets.find((x:Row)=>x.id===line.betTypeId)?.code;const tokens=line.selection.replaceAll('-',' ').split(' ').filter((value:string)=>value.length===2);values.push(...tokens);if(code==='LOTO3'||code==='LOTO4'||code==='LOTO5'){const digits=line.selection.replaceAll('-','').replaceAll(' ','');for(let i=0;i+1<digits.length;i+=2)values.push(digits.slice(i,i+2));if(digits.length>=3&&digits.length%2)values.push(digits.slice(-2))}}const unique=[...new Set(values)];if(unique.length<2)return[];return[{selection:[unique[0],unique[1]]},{selection:[unique[0],unique[2]??unique[1]]}]}
 function handleSale(e:FormEvent<HTMLFormElement>){if(total<100){submit(e,[]);return}if(!bets.some((x:Row)=>x.code==='MARYAJ')){e.preventDefault();setSaleError('Maryaj pa aktive sou tiraj sa a; pa ka ajoute 2 Maryaj gratis.');return}const gifts=freeMaryaj();if(gifts.length!==2){e.preventDefault();setSaleError('Chwazi nimewo pou de Maryaj gratis yo anvan vant lan.');openBonus(form(e.currentTarget));return}setSaleError('');submit(e,gifts)}
 function add(){const clean=number.replace(/\D/g,'');if(clean.length<2||clean.length>5||!(Number(entryStake)>0))return;const bet=bets.find((x:Row)=>x.code===codeFor(clean.length));if(!bet)return;setLines([...lines,{betTypeId:bet.id,betName:bet.name,selection:clean,stake:entryStake,resultPosition:clean.length===2?1:undefined}]);setNumber('');setEntryStake('')}
 function addMaryaj(){const bet=bets.find((x:Row)=>x.code==='MARYAJ');if(!bet||bolet.length<2||!(Number(maryajAutoStake)>0))return;setLines([...lines,...buildAutomaticMaryaj(bolet,bet,maryajAutoStake)]);setAutoDialog(null)}
 function addBoulPe(){const bet=bets.find((x:Row)=>x.code==='BOUL_PE');if(!bet||!(Number(boulPeStake)>0))return;setLines([...lines,...buildAutomaticBoulPe(bet,boulPeStake)]);setAutoDialog(null)}
 function addAutoLoto4(){const bet=bets.find((x:Row)=>x.code==='LOTO4');if(!bet||bolet.length<2||!(Number(lotoStake)>0)||!positions.length)return;setLines([...lines,...buildAutomaticLoto4(bolet,bet,lotoStake,positions)]);setAutoDialog(null)}
 const total=lines.reduce((sum:number,line:BetLine)=>sum+Number(line.stake||0),0);
 return <section className="panel sell"><div className="sell-heading"><div><span className="eyebrow">{t('sellDesk')}</span><h2>{t('sell')}</h2><p>{t('sellHelp')}</p></div><strong className="sale-total">{t('total')}<span>${cash(total)}</span></strong></div><form onSubmit={handleSale}>
  <div className="sell-draw-grid"><label>{t('openDraw')}<select name="drawId" value={draw} onChange={e=>{setDraw(e.target.value);setLines([])}} required><option value="">{t('choose')}</option>{s.draws?.map((x:Row)=><option value={x.id} key={x.id}>{drawLabel(x,language)}</option>)}</select></label><label>{t('printer')}<select name="printerId"><option value="">{t('autoPrint')}</option>{s.printers?.map((x:Row)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>{t('template')}<select name="templateId"><option value="">{t('choose')}</option>{s.templates?.filter((x:Row)=>x.kind==='TICKET').map((x:Row)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div>
  <section className="sell-entry"><div className="form-grid"><label>{t('ball')}<input value={number} inputMode="numeric" maxLength={5} autoFocus placeholder="12, 123, 1234, 12345" onChange={e=>setNumber(e.target.value.replace(/\D/g,''))}/></label><label>{t('ballPrice')}<input value={entryStake} type="number" min=".01" step=".01" onChange={e=>setEntryStake(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();add()}}}/></label><button type="button" onClick={add}>{t('addBall')}</button></div>
  </section>
  <div className="auto-tools"><div className="auto-tools-title"><div><h3>{t('autoTools')}</h3><small>{t('automaticNumbersCount').replace('{count}',String(bolet.length))}</small></div><button type="button" className="secondary" onClick={()=>setToolMenuOpen(true)}>{t('openTools')}</button></div></div>
  {lines.map((line:BetLine,index:number)=><div className="bet-line" key={`${line.selection}-${line.resultPosition}-${index}`}><b>{line.selection}</b><span>{line.betName}{line.resultPosition?` · ${t('option')} ${line.resultPosition}`:''}</span><label>{t('price')}<input value={line.stake} type="number" min=".01" step=".01" onChange={e=>setLines(lines.map((x:BetLine,i:number)=>i===index?{...x,stake:e.target.value}:x))}/></label><button type="button" className="danger" aria-label={t('removeLine')} onClick={()=>setLines(lines.filter((_:BetLine,i:number)=>i!==index))}>×</button></div>)}
  {total>=100&&<p className="bonus-message">Jwe pou 100 goud oswa plis: 2 Maryaj gratis.</p>}{saleError&&<p className="message">{saleError}</p>}<div className="ticket-actions"><b>{t('lineCount').replace('{count}',String(lines.length))} · {t('total')}: ${cash(total)}</b><button disabled={!online||!draw||!lines.length}>{t('validate')}</button></div></form>
  {toolMenuOpen&&<div className="dialog-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setToolMenuOpen(false)}}><section className="auto-dialog tool-menu-dialog" role="dialog" aria-modal="true" aria-labelledby="tool-menu-title"><button type="button" className="dialog-close secondary" aria-label={t('close')} onClick={()=>setToolMenuOpen(false)}>×</button><span className="eyebrow">{t('autoTools')}</span><h3 id="tool-menu-title">{t('moreTools')}</h3><p>{t('automaticNumbersCount').replace('{count}',String(bolet.length))}</p><div className="automatic-tool-list"><button type="button" className="secondary" disabled={!bets.some((x:Row)=>x.code==='MARYAJ')} onClick={()=>{setToolMenuOpen(false);setManualOpen(true)}}>{t('manualMaryaj')}</button><button type="button" disabled={!bets.some((x:Row)=>x.code==='MARYAJ')} onClick={()=>{setToolMenuOpen(false);setAutoDialog('maryaj')}}>{t('marriage')}</button><button type="button" disabled={!bets.some((x:Row)=>x.code==='LOTO4')} onClick={()=>{setToolMenuOpen(false);setAutoDialog('loto')}}>{t('autoLoto')}</button><button type="button" className="secondary" disabled={!bets.some((x:Row)=>x.code==='BOUL_PE')} onClick={()=>{setToolMenuOpen(false);setAutoDialog('boulPe')}}>{t('pair')}</button></div></section></div>}
  {autoDialog&&<div className="dialog-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setAutoDialog(null)}}><section className="auto-dialog" role="dialog" aria-modal="true" aria-labelledby="auto-dialog-title"><button type="button" className="dialog-close secondary" aria-label={t('close')} onClick={()=>setAutoDialog(null)}>×</button><span className="eyebrow">{t('autoTools')}</span><h3 id="auto-dialog-title">{autoDialog==='maryaj'?t('maryajDialogTitle'):autoDialog==='loto'?t('lotoDialogTitle'):t('boulPeDialogTitle')}</h3><p>{autoDialog==='maryaj'?t('maryajDialogHelp'):autoDialog==='loto'?t('lotoDialogHelp'):t('boulPeDialogHelp')}</p><div className="bolet-chips">{(autoDialog==='boulPe'?boulPeNumbers:bolet).map(value=><span key={value}>{value}</span>)}</div>{autoDialog==='loto'&&<div className="dialog-positions"><b>{t('position')}</b><div className="buttons">{[1,2,3].map(position=><button type="button" key={position} className={positions.includes(position)?'active':'secondary'} onClick={()=>setPositions(positions.includes(position)?positions.filter(x=>x!==position):[...positions,position].sort())}>{position===1?t('firstPosition'):`${position}${t('positionSuffix')}`}</button>)}<button type="button" className={positions.length===3?'active':'secondary'} onClick={()=>setPositions([1,2,3])}>{t('allOptions')}</button></div></div>}<label>{t('linePrice')}<input autoFocus value={autoDialog==='maryaj'?maryajAutoStake:autoDialog==='loto'?lotoStake:boulPeStake} type="number" min=".01" step=".01" onChange={e=>autoDialog==='maryaj'?setMaryajAutoStake(e.target.value):autoDialog==='loto'?setLotoStake(e.target.value):setBoulPeStake(e.target.value)}/></label><small>{t('editableLines')}</small><div className="buttons dialog-actions"><button type="button" className="secondary" onClick={()=>setAutoDialog(null)}>{t('cancelDialog')}</button><button type="button" onClick={autoDialog==='maryaj'?addMaryaj:autoDialog==='loto'?addAutoLoto4:addBoulPe} disabled={(autoDialog==='boulPe'?!(Number(boulPeStake)>0):bolet.length<2||!(Number(autoDialog==='maryaj'?maryajAutoStake:lotoStake)>0)||(autoDialog==='loto'&&!positions.length))}>{t('generate')}</button></div></section></div>}
  {manualOpen&&<ManualMaryajDialog language={language} onClose={()=>setManualOpen(false)} onAdd={(selection,stake)=>{const bet=bets.find((x:Row)=>x.code==='MARYAJ');if(!bet)return;setLines([...lines,{betTypeId:bet.id,betName:bet.name,selection:selection.join(' '),stake}]);setManualOpen(false)}}/>}
 </section>
}
function LiveResults({request}:{request:(path:string)=>Promise<any>}){const{t,language}=useMerchantLanguage();const[rows,setRows]=useState<Row[]>([]),[error,setError]=useState('');useEffect(()=>{let active=true;const load=async()=>{try{const draws=await request('/lottery/draws');if(active){setRows(draws.filter((x:Row)=>x.status==='RESULT_PUBLISHED'));setError('')}}catch(e){if(active)setError(e instanceof Error?e.message:String(e))}};void load();const timer=setInterval(load,15000);return()=>{active=false;clearInterval(timer)}},[request]);return <section className="panel"><div className="title"><div><h2>{t('live')}</h2><small>{t('updates')}</small></div></div>{error&&<p className="message">{error}</p>}<div className="stats">{rows.map(row=><article key={row.id}>{row.game?.logoUrl&&<img src={row.game.logoUrl} alt={row.game?.name} style={{height:48,maxWidth:120,objectFit:'contain'}}/>}<span>{drawLabel(row,language)}</span><strong>{row.result?.winningKeys?.join(' · ')??'—'}</strong></article>)}</div>{!rows.length&&!error&&<p>{t('noResults')}</p>}</section>}
