import{BadRequestException}from'@nestjs/common';import{Prisma}from'@lottivexa/database';import{validateSelection}from'../lottery/lottery-policy';
export type PricedLine={betTypeId:string;selection:number[];stake:string;resultPosition?:number;odds:string;selectionCount:number;numberMin:number;numberMax:number;allowRepeats:boolean};
export function chooseOdds<T extends {betTypeId:string;resultPosition:number|null}>(odds:T[],betTypeId:string,position?:number){return odds.find(x=>x.betTypeId===betTypeId&&x.resultPosition===position)??odds.find(x=>x.betTypeId===betTypeId&&x.resultPosition===null)}
export function priceLines(lines:PricedLine[]){if(!lines.length)throw new BadRequestException('TICKET_EMPTY');return lines.map(line=>{validateSelection(line.selection,line.selectionCount,line.numberMin,line.numberMax,line.allowRepeats);if(line.resultPosition!==undefined&&![1,2,3].includes(line.resultPosition))throw new BadRequestException('INVALID_RESULT_POSITION');const stake=new Prisma.Decimal(line.stake);const odds=new Prisma.Decimal(line.odds);if(!stake.gt(0)||!odds.gt(0))throw new BadRequestException('INVALID_AMOUNT');return{...line,selectionKey:`${line.selection.join('-')}${line.resultPosition?`@${line.resultPosition}`:''}`,stake,potentialWin:stake.mul(odds).toDecimalPlaces(4)}})}
export function resultWinningKeys(result:unknown):Set<string>{if(!result||typeof result!=='object'||!Array.isArray((result as{winningKeys?:unknown}).winningKeys))throw new BadRequestException('INVALID_RESULT_FORMAT');const keys=(result as{winningKeys:unknown[]}).winningKeys;if(keys.some(k=>typeof k!=='string'))throw new BadRequestException('INVALID_RESULT_FORMAT');return new Set(keys as string[])}
export function isWinningSelection(betTypeCode:string,storedSelectionKey:string,winningKeys:Set<string>){const[positionText,...keyParts]=storedSelectionKey.split('@').reverse(),hasPosition=storedSelectionKey.includes('@'),selectionKey=hasPosition?keyParts.reverse().join('@'):storedSelectionKey,resultPosition=hasPosition?Number(positionText):undefined,clean=(key:string)=>key.trim().replace(/^0+(?=\d)/,''),ordered=[...winningKeys].map(clean),normalized=new Set(ordered),selection=selectionKey.split('-').map(clean);if(betTypeCode==='MARYAJ')return selection.length===2&&selection.every(key=>normalized.has(key));if(resultPosition)return ordered[resultPosition-1]===clean(selectionKey);return normalized.has(clean(selectionKey))||normalized.has(selection.join('-'))}
export const BOUL_PE_NUMBERS=[0,11,22,33,44,55,66,77,88,99]as const;
export function validateHaitianBetType(code:string,selection:number[]){if(code==='BOUL_PE'&&(selection.length!==1||!BOUL_PE_NUMBERS.includes(selection[0]as typeof BOUL_PE_NUMBERS[number])))throw new BadRequestException('INVALID_BOUL_PE')}
export function cancellationDeadline(createdAt:Date,drawClosesAt:Date,seconds:number){if(!Number.isFinite(seconds)||seconds<0)throw new BadRequestException('INVALID_CANCELLATION_WINDOW');return new Date(Math.min(drawClosesAt.getTime(),createdAt.getTime()+seconds*1000))}
