import{BadRequestException,ForbiddenException,Injectable}from'@nestjs/common';
import{prisma}from'@lottivexa/database';
import type{Principal}from'../common/guards/jwt-auth.guard';
import{reportRange}from'./report-policy';
import{buildSalesPdf}from'./pdf-report';
@Injectable()export class ReportsService{
async sales(u:Principal,from?:string,to?:string){const tenantId=this.tenant(u),range=this.range(from,to),where={tenantId,createdAt:range};const[totals,statuses,branches,games,payouts,commissions]=await Promise.all([prisma.ticket.aggregate({where,_count:{_all:true},_sum:{amount:true,potentialWin:true,commission:true}}),prisma.ticket.groupBy({by:['status'],where,orderBy:{status:'asc'},_count:{_all:true},_sum:{amount:true}}),prisma.ticket.groupBy({by:['branchId'],where,orderBy:{branchId:'asc'},_count:{_all:true},_sum:{amount:true}}),prisma.ticket.groupBy({by:['gameId'],where,orderBy:{gameId:'asc'},_count:{_all:true},_sum:{amount:true}}),prisma.payout.aggregate({where:{tenantId,paidAt:range},_count:{_all:true},_sum:{amount:true}}),prisma.commissionTransaction.aggregate({where:{tenantId,createdAt:range},_sum:{commissionAmount:true}})]);return{period:{from:range.gte,to:range.lte},tickets:{count:totals._count._all,sales:totals._sum.amount?.toString()??'0',potentialWin:totals._sum.potentialWin?.toString()??'0',commission:totals._sum.commission?.toString()??'0'},payouts:{count:payouts._count._all,amount:payouts._sum.amount?.toString()??'0'},commission:commissions._sum.commissionAmount?.toString()??'0',byStatus:statuses.map(x=>({status:x.status,count:x._count._all,amount:x._sum.amount?.toString()??'0'})),byBranch:branches.map(x=>({branchId:x.branchId,count:x._count._all,amount:x._sum.amount?.toString()??'0'})),byGame:games.map(x=>({gameId:x.gameId,count:x._count._all,amount:x._sum.amount?.toString()??'0'}))}}
async pdf(u:Principal,from?:string,to?:string){const tenantId=this.tenant(u),[report,tenant]=await Promise.all([this.sales(u,from,to),prisma.tenant.findUniqueOrThrow({where:{id:tenantId},select:{legalName:true,branding:{select:{businessName:true}},settings:{select:{currency:true}}}})]);return buildSalesPdf(report,tenant.branding?.businessName??tenant.legalName,tenant.settings?.currency??'HTG')}
private range(from?:string,to?:string){try{return reportRange(from,to)}catch{throw new BadRequestException('INVALID_DATE_RANGE')}}
private tenant(u:Principal){if(!u.tenantId)throw new ForbiddenException('TENANT_ACCESS_REQUIRED');return u.tenantId}}
