'use client';
import{useEffect,useState}from'react';

const htFr:Record<string,string>={
'Platfòm':'Plateforme','Solisyon':'Solutions','Plan':'Forfaits','Rezilta':'Résultats','Konekte':'Connexion','Mande aksè':'Demander un accès',
'Sistèm bolet pwofesyonèl':'Système de loterie professionnel','Tout operasyon lotri ou.':'Toutes vos opérations de loterie.','Yon sèl platfòm.':'Une seule plateforme.',
'Kòmanse kounye a':'Commencer maintenant','Gade rezilta':'Voir les résultats','Done separe':'Données isolées','Sekirite pa wòl':'Sécurité par rôle','Sipò multi-aparèy':'Compatible multi-appareils',
'YON PLATFÒM KONPLÈ':'UNE PLATEFORME COMPLÈTE','Tout sa ou bezwen pou opere san dezòd.':'Tout ce dont vous avez besoin pour opérer efficacement.',
'Vann rapid':'Vente rapide','Rezilta ak gayan':'Résultats et gagnants','Enprime tout kote':'Imprimez partout','Travay offline':'Travail hors ligne','Finans ak komisyon':'Finances et commissions','Sekirite milti-tenant':'Sécurité multi-tenant','Aprann plis':'En savoir plus',
'OPERASYON SAN ENTERIPSYON':'OPÉRATIONS SANS INTERRUPTION','Sou kontwa a.':'Au comptoir.','Nan biwo a.':'Au bureau.','Tout kote.':'Partout.',
'Machann':'Vendeur','Sipèvizè':'Superviseur','Finans':'Finances','Administrasyon':'Administration','Nouvo tikè':'Nouveau ticket','Eskane QR':'Scanner le QR','Dènye aktivite':'Activité récente','Senkronizasyon fini':'Synchronisation terminée','Tout done yo ajou':'Toutes les données sont à jour',
'SENP POU KÒMANSE':'SIMPLE POUR COMMENCER','Soti nan enskripsyon rive nan premye vant ou.':'De l’inscription à votre première vente.','Kreye espas ou':'Créez votre espace','Konfigire operasyon':'Configurez vos opérations','Kòmanse vann':'Commencez à vendre',
'PLAN KI GRANDI AVÈK OU':'DES FORFAITS QUI ÉVOLUENT AVEC VOUS','Chwazi kapasite operasyon ou bezwen an.':'Choisissez la capacité dont votre activité a besoin.','Pou kòmanse':'Pour commencer','Pi popilè':'Le plus populaire','Sou mezi':'Sur mesure','REKÒMANDE':'RECOMMANDÉ','Chwazi plan sa a':'Choisir ce forfait',
'SEKIRITE PA KONSEPSYON':'SÉCURITÉ DÈS LA CONCEPTION','Kontwòl ou ka fè konfyans.':'Un contrôle digne de confiance.','Aksè pa wòl':'Accès par rôle','Tras konplè':'Traçabilité complète','Pwoteksyon done':'Protection des données',
'PRÈ POU MODÈNIZE OPERASYON OU?':'PRÊT À MODERNISER VOS OPÉRATIONS ?','Fè chak tikè konte.':'Faites compter chaque ticket.','Kontakte nou':'Nous contacter','Gade rezilta piblik':'Voir les résultats publics','Tout dwa rezève.':'Tous droits réservés.','Sistèm anliy':'Système en ligne',
'Akèy':'Accueil','Vant':'Ventes','Tikè':'Tickets','Rapò':'Rapports','Aparèy':'Appareils','Itilizatè':'Utilisateurs','Branch':'Succursales','Paramèt':'Paramètres','Dekonekte':'Déconnexion','Logout':'Déconnexion','Settings':'Paramètres',
'Soti':'Du','Rive':'Au','Afiche rapò':'Afficher le rapport','Telechaje PDF':'Télécharger le PDF','Peman gayan':'Paiements gagnants','Komisyon':'Commissions','Lotri ak tiraj (maten / swa)':'Loteries et tirages (matin / soir)','Maten':'Matin','Swa':'Soir','Pa estati':'Par statut','Dat':'Date','Tiraj':'Tirage','Nimewo tiraj':'Numéro du tirage','Estati':'Statut','Kantite':'Quantité','Montan':'Montant',
'Username':'Nom d’utilisateur','Password':'Mot de passe','Forgot password?':'Mot de passe oublié ?','Secure login':'Connexion sécurisée','Dashboard':'Tableau de bord','Health':'État du système','Billing':'Facturation','Subscriptions':'Abonnements','Tenants':'Clients',
'Afiche rezilta':'Afficher les résultats','Rezilta lotri':'Résultats de loterie','Pa gen rezilta pibliye.':'Aucun résultat publié.','AN TAN REYÈL':'EN TEMPS RÉEL'
,'Apèsi platfòm':'Aperçu de la plateforme','Rapò operasyon yo':'Rapports opérationnels','Chif aktyèl sou kliyan, abonnman, plan ak vant sou platfòm nan.':'Données actuelles sur les clients, abonnements, forfaits et ventes de la plateforme.','Done aktyèl':'Données actuelles','Kliyan aktif':'Clients actifs','Abonnman aktif':'Abonnements actifs','Revni abonnman':'Revenus des abonnements','Tikè vann':'Tickets vendus','Volim vant':'Volume des ventes','Distribisyon':'Répartition','Estati kliyan':'Statut des clients','Estati abonnman':'Statut des abonnements','Abonnman pa plan':'Abonnements par forfait','Distribisyon plan':'Répartition des forfaits','Pa gen done disponib.':'Aucune donnée disponible.','Pa gen abonnman ki lye ak yon plan pou kounye a.':'Aucun abonnement associé à un forfait pour le moment.','abonnman':'abonnement','Aktif':'Actif','Esè':'Essai','Anreta':'En retard','Sispann':'Suspendu','Anile':'Annulé','Achive':'Archivé'
};
const frHt=Object.fromEntries(Object.entries(htFr).map(([a,b])=>[b,a]));
const enHt:Record<string,string>={
 'Dashboard':'Tablo de bò','Plans':'Plan','Tenants':'Kliyan','Subscriptions':'Abonnman','Billing':'Faktirasyon','Reports':'Rapò','Health':'Eta sistèm nan','Games & Draws':'Lotri ak tiraj','Merchants':'Machann','Branches':'Biwo','Users & Roles':'Itilizatè ak wòl','Finance':'Finans','Devices':'Aparèy','Printers':'Enprimant','Settings & Domains':'Paramèt ak domèn','Audit Logs':'Jounal odit','Tickets':'Tikè',
 'MASTER ADMIN':'ADMINISTRATÈ PRENSIPAL','Logout':'Dekonekte','Create plan':'Kreye plan','Create Plan':'Kreye plan','Provision tenant':'Kreye kliyan','Provision Tenant':'Kreye kliyan',
 'Code':'Kòd','Name':'Non','Monthly price':'Pri pa mwa','Yearly price':'Pri pa ane','Currency':'Lajan','Active':'Aktif','Actions':'Aksyon','Archive':'Achive',
 'Professional':'Pwofesyonèl','Trial days':'Jou esè','Max merchants':'Kantite machann maksimòm','Max branches':'Kantite branch maksimòm','Max devices':'Kantite aparèy maksimòm',
 'Company name':'Non antrepriz','Owner email':'Imèl pwopriyetè','Owner username':'Non itilizatè pwopriyetè','Temporary password':'Modpas tanporè','Select plan':'Chwazi plan',
 'Activate':'Aktive','Suspend':'Sispann','Extend':'Pwolonje','Change plan':'Chanje plan','Reactivate':'Reyaktive','Invoice':'Fakti','Verify':'Verifye',
 'Username':'Non itilizatè','Password':'Modpas','Forgot password?':'Ou bliye modpas la?','Secure login':'Koneksyon sekirize'
 ,'Merchant Login':'Koneksyon machann','Tenant Admin':'Administrasyon kliyan','Master Admin Console':'Administrasyon prensipal','Tenant':'Espas biznis','Tenant / subdomain':'Espas biznis / sou-domèn','Username / Phone':'Non itilizatè / Telefòn','Username / phone':'Non itilizatè / telefòn','Login':'Konekte','Admin biznis la dwe kreye kont ou. Pa gen Sign Up.':'Administratè biznis la dwe kreye kont ou. Pa gen enskripsyon.','Antre nan espas biznis ou. Pa gen enskripsyon merchant.':'Antre nan espas biznis ou. Se administratè a ki kreye kont machann yo.'
};
const enFr:Record<string,string>={
 'Dashboard':'Tableau de bord','Plans':'Forfaits','Tenants':'Clients','Subscriptions':'Abonnements','Billing':'Facturation','Reports':'Rapports','Health':'État du système','Games & Draws':'Loteries et tirages','Merchants':'Vendeurs','Branches':'Succursales','Users & Roles':'Utilisateurs et rôles','Finance':'Finances','Devices':'Appareils','Printers':'Imprimantes','Settings & Domains':'Paramètres et domaines','Audit Logs':'Journal d’audit','Tickets':'Tickets',
 'MASTER ADMIN':'ADMINISTRATEUR PRINCIPAL','Logout':'Déconnexion','Create plan':'Créer un forfait','Create Plan':'Créer un forfait','Provision tenant':'Créer un client','Provision Tenant':'Créer un client',
 'Code':'Code','Name':'Nom','Monthly price':'Prix mensuel','Yearly price':'Prix annuel','Currency':'Devise','Active':'Actif','Actions':'Actions','Archive':'Archiver',
 'Professional':'Professionnel','Trial days':'Jours d’essai','Max merchants':'Nombre maximal de vendeurs','Max branches':'Nombre maximal de succursales','Max devices':'Nombre maximal d’appareils',
 'Company name':'Nom de l’entreprise','Owner email':'E-mail du propriétaire','Owner username':'Nom d’utilisateur du propriétaire','Temporary password':'Mot de passe temporaire','Select plan':'Choisir un forfait',
 'Activate':'Activer','Suspend':'Suspendre','Extend':'Prolonger','Change plan':'Changer de forfait','Reactivate':'Réactiver','Invoice':'Facture','Verify':'Vérifier',
 'Username':'Nom d’utilisateur','Password':'Mot de passe','Forgot password?':'Mot de passe oublié ?','Secure login':'Connexion sécurisée'
 ,'Merchant Login':'Connexion vendeur','Tenant Admin':'Administration client','Master Admin Console':'Administration principale','Tenant':'Espace professionnel','Tenant / subdomain':'Espace professionnel / sous-domaine','Username / Phone':'Nom d’utilisateur / Téléphone','Username / phone':'Nom d’utilisateur / téléphone','Login':'Connexion','Admin biznis la dwe kreye kont ou. Pa gen Sign Up.':'L’administrateur de l’entreprise doit créer votre compte. Aucune inscription publique.','Antre nan espas biznis ou. Pa gen enskripsyon merchant.':'Accédez à votre espace professionnel. Les comptes vendeurs sont créés par un administrateur.'
};
const tenantHaitian:Record<string,string>={
 'Sales':'Vant','Payouts':'Peman gayan','Net':'Nèt','Tickets':'Tikè','Branches':'Biwo','Merchants':'Machann','Unread alerts':'Alèt ki poko li','Recent tickets':'Dènye tikè yo','Today':'Jodi a','From':'Soti','To':'Rive','Run report':'Afiche rapò','Download PDF':'Telechaje PDF','By status':'Pa estati','By draw':'Pa tiraj','By game':'Pa lotri','By branch':'Pa biwo','Draw':'Tiraj','Game':'Lotri','Count':'Kantite','Amount':'Montan','Status':'Estati','Actions':'Aksyon','Name':'Non','Code':'Kòd','Date':'Dat','Number':'Nimewo','Create branch':'Kreye biwo','Create merchant account':'Kreye kont machann','Display name':'Non pou parèt','Merchant number':'Nimewo machann','Username':'Non itilizatè','Phone':'Telefòn','Email':'Imèl','Temporary password':'Modpas tanporè','Branch':'Biwo','Create':'Kreye','Create user':'Kreye itilizatè','Role':'Wòl','Users':'Itilizatè yo','Roles':'Wòl yo','Printers':'Enprimant','Add printer':'Ajoute enprimant','Connection':'Koneksyon','Protocol':'Pwotokòl','Default':'Pa defo','Branding':'Idantite biznis','Business settings':'Paramèt biznis','Save settings':'Sove paramèt','Custom domains':'Domèn pèsonalize','Add domain':'Ajoute domèn','Verify':'Verifye','Primary':'Prensipal','Games':'Lotri yo','Draws':'Tiraj yo','Create game':'Kreye lotri','Create draw':'Kreye tiraj','Result digits':'Chif rezilta','Open':'Ouvri','Close':'Fèmen','Activate':'Aktive','Settings & Domains':'Paramèt ak domèn','Games & Draws':'Lotri ak tiraj','Users & Roles':'Itilizatè ak wòl','Reports':'Rapò','Finance':'Finans','Devices':'Aparèy','Audit Logs':'Jounal odit','Tenant Admin':'Administrasyon biznis','TENANT CONSOLE':'ESPAS BIZNIS','Ticket':'Tikè','Potential win':'Gany posib','Session':'Sesyon','Morning':'Maten','Evening':'Swa','Password change':'Chanjman modpas','Create & attach bet type':'Kreye epi konekte kalite jwèt','Bet type kreye epi konekte ak game lan.':'Kalite jwèt la kreye epi konekte ak lotri a.','Result published and tickets updated automatically.':'Rezilta pibliye; tikè yo mete ajou otomatikman.'
};
const tenantFrench:Record<string,string>={
 'Sales':'Ventes','Payouts':'Gains payés','Net':'Net','Tickets':'Tickets','Branches':'Succursales','Merchants':'Vendeurs','Unread alerts':'Alertes non lues','Recent tickets':'Tickets récents','Today':'Aujourd’hui','From':'Du','To':'Au','Run report':'Afficher le rapport','Download PDF':'Télécharger le PDF','By status':'Par statut','By draw':'Par tirage','By game':'Par loterie','By branch':'Par succursale','Draw':'Tirage','Game':'Loterie','Count':'Quantité','Amount':'Montant','Status':'Statut','Actions':'Actions','Name':'Nom','Code':'Code','Date':'Date','Number':'Numéro','Create branch':'Créer une succursale','Create merchant account':'Créer un compte vendeur','Display name':'Nom affiché','Merchant number':'Numéro du vendeur','Username':'Identifiant','Phone':'Téléphone','Email':'E-mail','Temporary password':'Mot de passe temporaire','Branch':'Succursale','Create':'Créer','Create user':'Créer un utilisateur','Role':'Rôle','Users':'Utilisateurs','Roles':'Rôles','Printers':'Imprimantes','Add printer':'Ajouter une imprimante','Connection':'Connexion','Protocol':'Protocole','Default':'Par défaut','Branding':'Identité visuelle','Business settings':'Paramètres de l’entreprise','Save settings':'Enregistrer les paramètres','Custom domains':'Domaines personnalisés','Add domain':'Ajouter un domaine','Verify':'Vérifier','Primary':'Principal','Games':'Loteries','Draws':'Tirages','Create game':'Créer une loterie','Create draw':'Créer un tirage','Result digits':'Chiffres du résultat','Open':'Ouvrir','Close':'Fermer','Activate':'Activer','Settings & Domains':'Paramètres et domaines','Games & Draws':'Loteries et tirages','Users & Roles':'Utilisateurs et rôles','Reports':'Rapports','Finance':'Finances','Devices':'Appareils','Audit Logs':'Journal d’audit','Tenant Admin':'Administration de l’entreprise','TENANT CONSOLE':'ESPACE PROFESSIONNEL','Ticket':'Ticket','Potential win':'Gain potentiel','Session':'Séance','Morning':'Matin','Evening':'Soir','Password change':'Changement de mot de passe','Create & attach bet type':'Créer et associer un type de jeu'
};
Object.assign(enHt,tenantHaitian);Object.assign(enFr,tenantFrench);for(const[key,value]of Object.entries(tenantHaitian)){const french=tenantFrench[key]??value;htFr[value]=french;frHt[french]=value}
const sourceText=new WeakMap<Text,string>();const renderedText=new WeakMap<Text,string>();
const sourcePlaceholder=new WeakMap<HTMLElement,string>();const renderedPlaceholder=new WeakMap<HTMLElement,string>();
const legacy1252:Record<number,number>={8364:128,8218:130,402:131,8222:132,8230:133,8224:134,8225:135,710:136,8240:137,352:138,8249:139,338:140,381:142,8216:145,8217:146,8220:147,8221:148,8226:149,8211:150,8212:151,732:152,8482:153,353:154,8250:155,339:156,382:158,376:159};
function repairMojibake(value:string){return value.replace(/\S+/g,token=>{if(!/[ÃÂâï]/.test(token))return token;const bytes:number[]=[];for(const character of token){const point=character.codePointAt(0)!;const byte=point<=255?point:legacy1252[point];if(byte===undefined)return token;bytes.push(byte)}try{const repaired=new TextDecoder('utf-8',{fatal:true}).decode(new Uint8Array(bytes));return /[ÃÂâï]/.test(repaired)?token:repaired}catch{return token}})}
function translate(root:ParentNode,language:'ht'|'fr'){
 const dictionary=language==='fr'?{...enFr,...htFr}:{...enHt,...frHt};
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);
 const nodes:Text[]=[];while(walker.nextNode())nodes.push(walker.currentNode as Text);
 for(const node of nodes){if(node.parentElement?.closest('[data-language-switcher]'))continue;const raw=node.nodeValue??'',last=renderedText.get(node);let original=sourceText.get(node);if(original===undefined||last!==raw){original=raw;sourceText.set(node,original)}const trimmed=original.trim(),translated=dictionary[trimmed],next=translated?original.replace(trimmed,translated):original;if(node.nodeValue!==next)node.nodeValue=next;renderedText.set(node,next)}
 root.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('[placeholder]').forEach(input=>{const raw=input.placeholder,last=renderedPlaceholder.get(input);let original=sourcePlaceholder.get(input);if(original===undefined||last!==raw){original=raw;sourcePlaceholder.set(input,original)}const next=dictionary[original]??original;if(input.placeholder!==next)input.placeholder=next;renderedPlaceholder.set(input,next)});
}
export function LanguageSwitcher(){
 const[language,setLanguage]=useState<'ht'|'fr'>('ht');
 const[waking,setWaking]=useState(false);
 const[open,setOpen]=useState(false);
 useEffect(()=>{let cancelled=false;const raw=process.env.NEXT_PUBLIC_API_URL??'http://localhost:4000',base=raw.replace(/\/$/,'').endsWith('/api/v1')?raw.replace(/\/$/,''):raw.replace(/\/$/,'')+'/api/v1';async function warm(attempt=0){try{const response=await fetch(base+'/health',{cache:'no-store'});if(!response.ok)throw new Error('NOT_READY');if(!cancelled)setWaking(false)}catch{if(!cancelled){setWaking(true);if(attempt<6)setTimeout(()=>void warm(attempt+1),10_000)}}}void warm();return()=>{cancelled=true}},[]);
 useEffect(()=>{const saved=localStorage.getItem('lottivexa-language');const initial=saved==='fr'?'fr':'ht';setLanguage(initial);document.documentElement.lang=initial;translate(document.body,initial)},[]);
 useEffect(()=>{document.documentElement.lang=language;localStorage.setItem('lottivexa-language',language);window.dispatchEvent(new CustomEvent('lottivexa-language-change',{detail:language}));translate(document.body,language);const observer=new MutationObserver(records=>{for(const record of records){for(const node of record.addedNodes)if(node.nodeType===Node.ELEMENT_NODE||node.nodeType===Node.TEXT_NODE)translate(node.nodeType===Node.TEXT_NODE?(node.parentNode??document.body) as ParentNode:node as ParentNode,language);if(record.type==='characterData')translate((record.target.parentNode??document.body) as ParentNode,language)}});observer.observe(document.body,{childList:true,subtree:true,characterData:true});return()=>observer.disconnect()},[language]);
 return <>{waking&&<div data-language-switcher className="serverWake" role="status"><span className="wakeSpinner"/> {language==='fr'?'Serveur en cours de démarrage…':'Sèvè a ap reveye…'}</div>}<div data-language-switcher className="languageSwitcher" role="group" aria-label="Langue / Lang"><button type="button" className="languageToggle" aria-expanded={open} onClick={()=>setOpen(value=>!value)}>🌐 {language==='fr'?'Français':'Kreyòl'} <span aria-hidden="true">⌄</span></button>{open&&<div className="languageMenu"><button type="button" className={language==='ht'?'active':''} onClick={()=>{setLanguage('ht');setOpen(false)}}>Kreyòl</button><button type="button" className={language==='fr'?'active':''} onClick={()=>{setLanguage('fr');setOpen(false)}}>Français</button></div>}</div></>
}
