import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../core/mobile_runtime.dart';
import '../../core/localization/app_language.dart';
import '../../core/printing/printer_transport.dart';

class SettingsScreen extends StatefulWidget {
  const SettingsScreen({super.key, required this.runtime});
  final MobileRuntime runtime;
  @override State<SettingsScreen> createState()=>_State();
}
class _State extends State<SettingsScreen>{
  List<Map<String,dynamic>>printers=[],nearby=[];
  String nearbyType='BLUETOOTH',timezone='America/Port-au-Prince',locale='ht-HT',dateFormat='DD/MM/YYYY';String?message;bool busy=false;
  @override void initState(){super.initState();load();}
  Future<void>load()async{try{final response=await widget.runtime.api.dio.get<List<dynamic>>('/api/v1/printing/printers');if(mounted)setState(()=>printers=(response.data??[]).map((x)=>Map<String,dynamic>.from(x as Map)).toList());if(widget.runtime.session.hasPermission('settings.edit')){final settings=await widget.runtime.api.dio.get<Map<String,dynamic>>('/api/v1/settings');final saved=Map<String,dynamic>.from((settings.data?['settings'] as Map?)??{});if(mounted)setState((){timezone='${saved['timezone']??timezone}';locale='${saved['locale']??locale}';dateFormat='${saved['dateFormat']??dateFormat}';});}if(mounted)setState(()=>message=null);}catch(error){if(mounted)setState(()=>message='Done paramèt yo oswa printer branch lan pa disponib: $error');}}
  Future<void>saveCurrency(String value)async{setState(()=>busy=true);try{await widget.runtime.api.dio.put('/api/v1/settings',data:{'currency':value,'timezone':timezone,'locale':locale,'dateFormat':dateFormat});if(mounted)setState(()=>message=AppLanguage.tr('Lajan tikè a sove.'));}catch(error){if(mounted)setState(()=>message='Paramèt la pa sove: $error');}finally{if(mounted)setState(()=>busy=false);}}
  Future<void>sync()async{setState(()=>busy=true);try{await widget.runtime.prepareDevice();await widget.runtime.recover();if(mounted)setState(()=>message=widget.runtime.deviceId==null?'Aparèy la anrejistre otomatikman; administratè a dwe apwouve l pou lavant offline. Pa efase done aplikasyon an.':'Sync fini. ${widget.runtime.pendingCount} ap tann, ${widget.runtime.store.rejectedCount} rejte; ${widget.runtime.printer.pendingCount} enpresyon ap tann.');}catch(error){if(mounted)setState(()=>message='Sync pa fèt: $error');}finally{if(mounted)setState(()=>busy=false);}}
  Future<void>scan(String type)async{setState((){busy=true;nearbyType=type;nearby=[];});try{final found=await widget.runtime.printer.discover(type);if(mounted)setState((){nearby=found;message=found.isEmpty?'Pa gen printer $type ki pare. Limen/pair printer la epi chèche ankò.':'${found.length} printer jwenn. Peze KONEKTE sou printer ou vle a.';});}catch(error){if(mounted)setState(()=>message='Android pa ka chèche printer la: $error');}finally{if(mounted)setState(()=>busy=false);}}
  Future<void>connect(Map<String,dynamic>item)async{setState(()=>busy=true);try{await widget.runtime.printer.connectLocal(nearbyType,item);if(mounted)setState(()=>message='${item['name']??'Printer'} konekte, teste epi chwazi kòm printer default.');}catch(error){if(mounted)setState(()=>message='Koneksyon/enpresyon tès la echwe: $error');}finally{if(mounted)setState(()=>busy=false);}}
  Future<void>test(Map<String,dynamic>printer)async{setState(()=>busy=true);try{await widget.runtime.printer.test(printer);widget.runtime.printer.setDefaultPrinter(printer['id'].toString());if(mounted)setState(()=>message='Test page enprime; ${printer['name']} se printer default la.');}catch(error){if(mounted)setState(()=>message='Printer pa enprime: $error');}finally{if(mounted)setState(()=>busy=false);}}
  @override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(20),children:[
    Text(AppLanguage.tr('Plis'),style:const TextStyle(fontSize:26,fontWeight:FontWeight.bold)),
    Card(child:Wrap(spacing:8,runSpacing:8,alignment:WrapAlignment.center,children:[
      OutlinedButton.icon(onPressed:()=>context.go('/results'),icon:const Icon(Icons.emoji_events_outlined),label:Text(AppLanguage.tr('Rezilta'))),
      if(widget.runtime.session.hasPermission('finance.view'))OutlinedButton.icon(onPressed:()=>context.go('/cash'),icon:const Icon(Icons.point_of_sale_outlined),label:Text(AppLanguage.tr('Kès'))),
      if(widget.runtime.session.hasPermission('reports.view'))OutlinedButton.icon(onPressed:()=>context.go('/reports'),icon:const Icon(Icons.bar_chart_outlined),label:Text(AppLanguage.tr('Rapò'))),
    ])),
    ValueListenableBuilder<Locale>(valueListenable:AppLanguage.current,builder:(_,locale,__)=>Card(child:ListTile(leading:const Icon(Icons.language),title:Text(AppLanguage.tr('Lang aplikasyon an')),trailing:DropdownButton<String>(value:locale.languageCode,items:const[DropdownMenuItem(value:'ht',child:Text('Kreyòl')),DropdownMenuItem(value:'fr',child:Text('Français'))],onChanged:(value){if(value!=null)AppLanguage.set(value);})))),
    if(widget.runtime.session.hasPermission('settings.edit'))Card(child:ListTile(leading:const Icon(Icons.attach_money),title:Text(AppLanguage.tr('Lajan tikè ak rapò')),subtitle:Text(AppLanguage.tr('Siy dola pou pri tikè ak rapò.')),trailing:Row(mainAxisSize:MainAxisSize.min,children:[const Text('\$'),IconButton(tooltip:AppLanguage.tr('Anrejistre siy dola a'),onPressed:busy?null:()=>saveCurrency('USD'),icon:const Icon(Icons.save_outlined))]))),
    Text(AppLanguage.tr('Senkronizasyon ak enprimant'),style:TextStyle(fontSize:26,fontWeight:FontWeight.bold)),
    StreamBuilder<List<ConnectivityResult>>(stream:Connectivity().onConnectivityChanged,builder:(_,snapshot){final online=snapshot.data?.any((x)=>x!=ConnectivityResult.none)??true;return ListTile(leading:Icon(online?Icons.cloud_done:Icons.cloud_off),title:Text(online?'Online':'Offline'),subtitle:Text('${widget.runtime.pendingCount} ${AppLanguage.tr('Ap tann senkronizasyon')} · ${widget.runtime.printer.pendingCount} ${AppLanguage.tr('Enpresyon an atant')}'));}),
    ExpansionTile(title:Text(AppLanguage.tr('Aparèy POS sa a')),children:[ListTile(title:Text(AppLanguage.tr(widget.runtime.deviceId==null?'Ap tann apwobasyon administratè a':'Aparèy apwouve')),subtitle:Text(widget.runtime.deviceStatus??'Lè entènèt disponib, aparèy la ap anrejistre otomatikman.')),FilledButton.icon(onPressed:busy?null:sync,icon:const Icon(Icons.sync),label:Text(AppLanguage.tr('Tcheke epi senkronize')))]),
    if(widget.runtime.store.rejectedCount>0||widget.runtime.store.syncErrors.isNotEmpty)Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Tikè ki pa senkronize: pa efase done app la.',style:TextStyle(fontWeight:FontWeight.bold)),for(final item in widget.runtime.store.syncErrors)Text('${item['status']}: ${item['error']}')]))),
    const Divider(),const Text('Konekte yon printer',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const Text('Ou pa bezwen antre ID printer la. Limen printer la, epi chèche li.'),const SizedBox(height:10),
    Wrap(spacing:8,runSpacing:8,children:[FilledButton.icon(onPressed:busy?null:()=>scan('BLUETOOTH'),icon:const Icon(Icons.bluetooth_searching),label:const Text('Chèche Bluetooth')),OutlinedButton.icon(onPressed:busy?null:()=>scan('USB'),icon:const Icon(Icons.usb),label:const Text('Chèche USB')),OutlinedButton.icon(onPressed:busy?null:()async{await widget.runtime.printer.useSystemPrinter();if(mounted)setState(()=>message='Enprime nòmal Android chwazi. Apre vant, telefòn lan ap montre lis printer Android yo.');},icon:const Icon(Icons.print),label:const Text('Enprime nòmal')),TextButton.icon(onPressed:()=>NativePrinterTransport('BLUETOOTH').openBluetoothSettings(),icon:const Icon(Icons.settings_bluetooth),label:const Text('Pair nouvo printer'))]),
    for(final item in nearby)Card(child:ListTile(leading:Icon(nearbyType=='BLUETOOTH'?Icons.bluetooth:Icons.usb),title:Text(item['name']?.toString()??'Printer'),subtitle:Text(item['bonded']==true?'Pare pou konekte':'Printer detekte'),trailing:FilledButton(onPressed:busy?null:()=>connect(item),child:const Text('KONEKTE')))),
    if(widget.runtime.printer.localPrinter!=null)Card(color:Colors.green.shade50,child:ListTile(leading:const Icon(Icons.check_circle,color:Colors.green),title:Text('${widget.runtime.printer.localPrinter!['name']}'),subtitle:const Text('Printer mobil default • tikè ap enprime apre vant'))),
    const Divider(),Text(AppLanguage.tr('Enprimant biwo a'),style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),
    if(printers.isEmpty)const ListTile(title:Text('Pa gen lòt printer configure pou branch sa a.')),
    for(final printer in printers)Card(child:ListTile(leading:const Icon(Icons.print),title:Text(printer['name']?.toString()??'Printer'),subtitle:Text('${printer['connectionType']} • ${printer['status']}'),trailing:widget.runtime.printer.defaultPrinterId==printer['id']?const Icon(Icons.check_circle,color:Colors.green):null,onTap:busy?null:()=>test(printer))),
    if(message!=null)Padding(padding:const EdgeInsets.all(12),child:Text(message!,style:const TextStyle(fontWeight:FontWeight.w600))),
    const Divider(),OutlinedButton.icon(onPressed:widget.runtime.session.clear,icon:const Icon(Icons.logout),label:Text(AppLanguage.tr('Sòti')))]);
}
