import{BadRequestException,ForbiddenException,Injectable}from'@nestjs/common';import{DrawStatus,LimitScope,prisma,Prisma}from'@lottivexa/database';import type{Principal}from'../common/guards/jwt-auth.guard';import{assertDrawTimes,assertDrawTransition}from'./lottery-policy';import{installHaitiCatalog}from'./haiti-catalog-installer';
@Injectable()export class LotteryService{
 catalog(u:Principal){const tenantId=this.tenant(u);return prisma.game.findMany({where:{tenantId,catalogCode:{not:null}},include:{schedules:true,betTypes:{include:{betType:true}}},orderBy:{name:'asc'}})}
 async setCatalogStatus(u:Principal,catalogCode:string,enabled:boolean){const tenantId=this.tenant(u);const changed=await prisma.game.updateMany({where:{tenantId,catalogCode},data:{status:enabled?'ACTIVE':'SUSPENDED'}});if(changed.count!==1)throw new ForbiddenException('CATALOG_GAME_NOT_FOUND');await prisma.auditLog.create({data:{tenantId,userId:u.sub,action:'UPDATE',entityType:'LotteryCatalog',entityId:catalogCode,newValues:{enabled}}});return{catalogCode,enabled}}
 async installHaitiCatalog(u:Principal){const tenantId=this.tenant(u);return prisma.$transaction(async tx=>{const installed=await installHaitiCatalog(tx,tenantId);await tx.auditLog.create({data:{tenantId,userId:u.sub,action:'CREATE',entityType:'LotteryCatalog',entityId:'HT-V1',newValues:installed}});return{installed:true,...installed}})}
 async setScheduleStatus(u:Principal,id:string,enabled:boolean){const tenantId=this.tenant(u);const changed=await prisma.gameSchedule.updateMany({where:{id,tenantId},data:{active:enabled}});if(changed.count!==1)throw new ForbiddenException('SCHEDULE_NOT_FOUND');await prisma.auditLog.create({data:{tenantId,userId:u.sub,action:'UPDATE',entityType:'GameSchedule',entityId:id,newValues:{enabled}}});return{id,enabled}}

 games(u:Principal){const tenantId=this.tenant(u);return prisma.game.findMany({where:{tenantId,archivedAt:null},include:{betTypes:{include:{betType:true}},schedules:true,odds:true},orderBy:{name:'asc'}})}
 createGame(u:Principal,dto:{code:string;name:string;description?:string;cutoffSeconds:number;resultDigits:number}){const tenantId=this.tenant(u);return this.auditedCreate(tenantId,u.sub,'Game',()=>prisma.game.create({data:{tenantId,...dto}}))}
 async updateGame(u:Principal,id:string,dto:{name?:string;logoUrl?:string}){const tenantId=this.tenant(u);if(!dto.name&&!dto.logoUrl)throw new BadRequestException('NO_GAME_CHANGES');const old=await prisma.game.findFirst({where:{id,tenantId},select:{name:true,logoUrl:true}});if(!old)throw new ForbiddenException('RESOURCE_NOT_FOUND');const changed=await prisma.game.updateMany({where:{id,tenantId},data:dto});if(changed.count!==1)throw new BadRequestException('GAME_CONCURRENTLY_MODIFIED');await prisma.auditLog.create({data:{tenantId,userId:u.sub,action:'UPDATE',entityType:'Game',entityId:id,oldValues:old,newValues:dto}});return prisma.game.findFirstOrThrow({where:{id,tenantId}})}
 createMarket(u:Principal,dto:{code:string;name:string}){const tenantId=this.tenant(u);return this.auditedCreate(tenantId,u.sub,'Market',()=>prisma.market.create({data:{tenantId,...dto}}))}
 async createSchedule(u:Principal,dto:{gameId:string;marketId?:string;weekday:number;opensAt:string;closesAt:string;resultAt:string;timezone:string}){const tenantId=this.tenant(u);const game=await prisma.game.findFirst({where:{id:dto.gameId,tenantId}});const market=dto.marketId?await prisma.market.findFirst({where:{id:dto.marketId,tenantId}}):null;if(!game||(dto.marketId&&!market))throw new ForbiddenException('RESOURCE_NOT_FOUND');if(!(dto.opensAt<dto.closesAt&&dto.closesAt<=dto.resultAt))throw new BadRequestException('INVALID_SCHEDULE_TIMES');return this.auditedCreate(tenantId,u.sub,'GameSchedule',()=>prisma.gameSchedule.create({data:{tenantId,...dto}}))}
 createBetType(u:Principal,dto:{code:string;name:string;selectionCount:number;numberMin:number;numberMax:number;allowRepeats:boolean}){const tenantId=this.tenant(u);if(dto.numberMax<dto.numberMin)throw new BadRequestException('INVALID_NUMBER_RANGE');return this.auditedCreate(tenantId,u.sub,'BetType',()=>prisma.betType.create({data:{tenantId,...dto}}))}
 async attachBetType(u:Principal,gameId:string,betTypeId:string){const tenantId=this.tenant(u);const [game,bet]=await Promise.all([prisma.game.findFirst({where:{id:gameId,tenantId}}),prisma.betType.findFirst({where:{id:betTypeId,tenantId}})]);if(!game||!bet)throw new ForbiddenException('RESOURCE_NOT_FOUND');return prisma.gameBetType.upsert({where:{gameId_betTypeId:{gameId,betTypeId}},update:{active:true},create:{gameId,betTypeId}})}
 draws(u:Principal){const tenantId=this.tenant(u);return prisma.draw.findMany({where:{tenantId},include:{game:true},orderBy:{opensAt:'desc'},take:200})}
 async createDraw(u:Principal,dto:{gameId:string;drawNumber:string;drawDate:string;opensAt:string;closesAt:string;resultAt:string}){const tenantId=this.tenant(u);const game=await prisma.game.findFirst({where:{id:dto.gameId,tenantId,status:'ACTIVE'}});if(!game)throw new ForbiddenException('RESOURCE_NOT_FOUND');const opensAt=new Date(dto.opensAt),closesAt=new Date(dto.closesAt),resultAt=new Date(dto.resultAt);assertDrawTimes(opensAt,closesAt,resultAt);return this.auditedCreate(tenantId,u.sub,'Draw',()=>prisma.draw.create({data:{tenantId,gameId:game.id,drawNumber:dto.drawNumber,drawDate:new Date(dto.drawDate),opensAt,closesAt,resultAt,createdById:u.sub}}))}
 async transition(u:Principal,id:string,next:DrawStatus,result?:Record<string,unknown>){const tenantId=this.tenant(u);if(next==='RESULT_PUBLISHED')throw new BadRequestException('USE_RESULT_PUBLISH_ENDPOINT');return prisma.$transaction(async tx=>{const draw=await tx.draw.findFirst({where:{id,tenantId}});if(!draw)throw new ForbiddenException('RESOURCE_NOT_FOUND');assertDrawTransition(draw.status,next);const changed=await tx.draw.updateMany({where:{id,tenantId,status:draw.status},data:{status:next,result:result as Prisma.InputJsonValue|undefined}});if(changed.count!==1)throw new BadRequestException('DRAW_CONCURRENTLY_MODIFIED');const auditValues={status:next,...(result?{result}:{})}as Prisma.InputJsonValue;await tx.auditLog.create({data:{tenantId,userId:u.sub,action:'UPDATE',entityType:'Draw',entityId:id,oldValues:{status:draw.status},newValues:auditValues}});return tx.draw.findUniqueOrThrow({where:{id}})})}
async createOdds(u:Principal,dto:{gameId:string;betTypeId:string;multiplier:string;startsAt:string;endsAt?:string;resultPosition?:number}){const tenantId=this.tenant(u);const attached=await prisma.gameBetType.findFirst({where:{gameId:dto.gameId,betTypeId:dto.betTypeId,active:true,game:{tenantId},betType:{tenantId}},include:{betType:true}});if(!attached)throw new BadRequestException('BET_TYPE_NOT_ENABLED_FOR_GAME');if(!Number.isFinite(Number(dto.multiplier))||Number(dto.multiplier)<=0)throw new BadRequestException('INVALID_ODDS');if(dto.resultPosition!==undefined&&(attached.betType.code!=='BOLET'||![1,2,3].includes(dto.resultPosition)))throw new BadRequestException('INVALID_RESULT_POSITION');return prisma.oddsRule.create({data:{tenantId,gameId:dto.gameId,betTypeId:dto.betTypeId,resultPosition:dto.resultPosition,multiplier:dto.multiplier,startsAt:new Date(dto.startsAt),endsAt:dto.endsAt?new Date(dto.endsAt):undefined}})}
 createLimit(u:Principal,dto:{scope:LimitScope;scopeId?:string;gameId?:string;drawId?:string;betTypeId?:string;numberKey?:string;minStake?:string;maxStake?:string;maxExposure?:string;startsAt:string}){const tenantId=this.tenant(u);if(dto.minStake&&dto.maxStake&&Number(dto.maxStake)<Number(dto.minStake))throw new BadRequestException('INVALID_LIMIT_RANGE');return prisma.bettingLimit.create({data:{tenantId,...dto,startsAt:new Date(dto.startsAt)}})}
 createRule(u:Principal,dto:{jurisdictionCode:string;key:string;value:Record<string,unknown>;effectiveFrom:string;effectiveTo?:string}){const tenantId=this.tenant(u);return this.auditedCreate(tenantId,u.sub,'LotteryRule',()=>prisma.lotteryRule.create({data:{tenantId,jurisdictionCode:dto.jurisdictionCode,key:dto.key,value:dto.value as Prisma.InputJsonValue,effectiveFrom:new Date(dto.effectiveFrom),effectiveTo:dto.effectiveTo?new Date(dto.effectiveTo):undefined}}))}
 private async auditedCreate<T extends{id:string}>(tenantId:string,userId:string,entityType:string,create:()=>Promise<T>){const entity=await create();await prisma.auditLog.create({data:{tenantId,userId,action:'CREATE',entityType,entityId:entity.id}});return entity}
 private tenant(u:Principal){if(!u.tenantId)throw new ForbiddenException('TENANT_ACCESS_REQUIRED');return u.tenantId}
}
