import{BadRequestException,ForbiddenException,Injectable}from'@nestjs/common';import{DrawStatus,LimitScope,prisma,Prisma}from'@lottivexa/database';import type{Principal}from'../common/guards/jwt-auth.guard';import{assertDrawTimes,assertDrawTransition,assertScheduleTimes,assertPositionedOddsType,normalizeBoletMultipliers}from'./lottery-policy';import{isDrawScheduleEnabled}from'./draw-schedule-policy';import{installHaitiCatalog}from'./haiti-catalog-installer';import{currencyForCountry,COUNTRY_CURRENCY}from'../tenants/country-currency-policy';import{resolveFreeMaryajPolicy,validateFreeMaryajPolicy}from'../tickets/free-maryaj-policy';import{drawDateFilter}from'./draw-date-filter';import{scheduledDrawTimeUpdate,type ScheduleDrawTiming}from'./scheduled-draw-times';
@Injectable()export class LotteryService{
 catalog(u:Principal){const tenantId=this.tenant(u);return prisma.game.findMany({where:{tenantId,catalogCode:{not:null}},include:{schedules:true,betTypes:{include:{betType:true}}},orderBy:{name:'asc'}})}
 async setCatalogStatus(u:Principal,catalogCode:string,enabled:boolean){const tenantId=this.tenant(u);const changed=await prisma.game.updateMany({where:{tenantId,catalogCode},data:{status:enabled?'ACTIVE':'SUSPENDED'}});if(changed.count!==1)throw new ForbiddenException('CATALOG_GAME_NOT_FOUND');await prisma.auditLog.create({data:{tenantId,userId:u.sub,action:'UPDATE',entityType:'LotteryCatalog',entityId:catalogCode,newValues:{enabled}}});return{catalogCode,enabled}}
 async installHaitiCatalog(u:Principal){const tenantId=this.tenant(u);return prisma.$transaction(async tx=>{const installed=await installHaitiCatalog(tx,tenantId);await tx.auditLog.create({data:{tenantId,userId:u.sub,action:'CREATE',entityType:'LotteryCatalog',entityId:'HT-V1',newValues:installed}});return{installed:true,...installed}})}
 async setScheduleStatus(u:Principal,id:string,enabled:boolean){const tenantId=this.tenant(u);const changed=await prisma.gameSchedule.updateMany({where:{id,tenantId},data:{active:enabled}});if(changed.count!==1)throw new ForbiddenException('SCHEDULE_NOT_FOUND');await prisma.auditLog.create({data:{tenantId,userId:u.sub,action:'UPDATE',entityType:'GameSchedule',entityId:id,newValues:{enabled}}});return{id,enabled}}
 async setScheduleSlotStatus(u:Principal,dto:{gameId:string;resultAt:string;enabled?:boolean;opensAt?:string;closesAt?:string}){
  const tenantId=this.tenant(u);
  const hasOpensAt=dto.opensAt!==undefined;
  const hasClosesAt=dto.closesAt!==undefined;
  if(hasOpensAt!==hasClosesAt)throw new BadRequestException('INCOMPLETE_SCHEDULE_TIMES');
  if(dto.enabled===undefined&&!hasOpensAt)throw new BadRequestException('NO_SCHEDULE_SLOT_CHANGES');
  if(hasOpensAt)assertScheduleTimes(dto.opensAt!,dto.closesAt!,dto.resultAt);
  const where={tenantId,gameId:dto.gameId,resultAt:dto.resultAt};
  return prisma.$transaction(async tx=>{
   const schedules=await tx.gameSchedule.findMany({where,select:{id:true,active:true,opensAt:true,closesAt:true,resultAt:true,weekday:true,timezone:true}});
   if(!schedules.length)throw new ForbiddenException('SCHEDULE_NOT_FOUND');
   const data={
    ...(dto.enabled!==undefined?{active:dto.enabled}:{}),
    ...(hasOpensAt?{opensAt:dto.opensAt!,closesAt:dto.closesAt!}:{}),
   };
   await tx.gameSchedule.updateMany({where,data});
   const updatedDraws=hasOpensAt?await this.syncUpcomingScheduledDraws(tx,tenantId,dto.gameId,schedules.map(schedule=>({
    weekday:schedule.weekday,timezone:schedule.timezone,previousResultAt:schedule.resultAt,
    opensAt:dto.opensAt!,closesAt:dto.closesAt!,resultAt:schedule.resultAt,
   }))):0;
   await tx.auditLog.create({data:{
    tenantId,userId:u.sub,action:'UPDATE',entityType:'GameScheduleSlot',entityId:`${dto.gameId}:${dto.resultAt}`,
    oldValues:{enabled:schedules.some(schedule=>schedule.active),times:[...new Set(schedules.map(schedule=>`${schedule.opensAt}-${schedule.closesAt}`))]},
    newValues:{
     ...(dto.enabled!==undefined?{enabled:dto.enabled}:{}),
     ...(hasOpensAt?{opensAt:dto.opensAt,closesAt:dto.closesAt}:{}),
     updatedSchedules:schedules.length,updatedDraws,
    },
   }});
   return{
    gameId:dto.gameId,resultAt:dto.resultAt,
    ...(dto.enabled!==undefined?{enabled:dto.enabled}:{}),
    ...(hasOpensAt?{opensAt:dto.opensAt,closesAt:dto.closesAt}:{}),
    updatedSchedules:schedules.length,updatedDraws,
   };
  },{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});
 }
 async updateScheduleTimes(u:Principal,id:string,dto:{opensAt?:string;closesAt?:string;resultAt?:string}){const tenantId=this.tenant(u);return prisma.$transaction(async tx=>{const schedule=await tx.gameSchedule.findFirst({where:{id,tenantId}});if(!schedule)throw new ForbiddenException('SCHEDULE_NOT_FOUND');const opensAt=dto.opensAt??schedule.opensAt;const closesAt=dto.closesAt??schedule.closesAt;const resultAt=dto.resultAt??schedule.resultAt;assertScheduleTimes(opensAt,closesAt,resultAt);const updated=await tx.gameSchedule.update({where:{id},data:{opensAt,closesAt,resultAt}});const updatedDraws=await this.syncUpcomingScheduledDraws(tx,tenantId,schedule.gameId,[{weekday:schedule.weekday,timezone:schedule.timezone,previousResultAt:schedule.resultAt,opensAt,closesAt,resultAt}]);await tx.auditLog.create({data:{tenantId,userId:u.sub,action:'UPDATE',entityType:'GameSchedule',entityId:id,oldValues:{opensAt:schedule.opensAt,closesAt:schedule.closesAt,resultAt:schedule.resultAt},newValues:{opensAt,closesAt,resultAt,updatedDraws}}});return updated},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}

 settings(u:Principal){const tenantId=this.tenant(u);return prisma.game.findMany({where:{tenantId,archivedAt:null},include:{betTypes:{where:{active:true},include:{betType:true}},schedules:{include:{market:true},orderBy:[{weekday:'asc'},{opensAt:'asc'}]},odds:{where:{active:true},orderBy:{startsAt:'desc'}}},orderBy:{name:'asc'}})}
 async freeMaryajSettings(u:Principal,countryInput:string){const tenantId=this.tenant(u),countryCode=String(countryInput??'').trim().toUpperCase(),currency=currencyForCountry(countryCode);if(!currency)throw new BadRequestException('UNSUPPORTED_COUNTRY');const now=new Date(),rule=await prisma.lotteryRule.findFirst({where:{tenantId,jurisdictionCode:countryCode,key:'free_maryaj_policy',active:true,effectiveFrom:{lte:now},OR:[{effectiveTo:null},{effectiveTo:{gt:now}}]},orderBy:{effectiveFrom:'desc'}});return{...resolveFreeMaryajPolicy(countryCode,rule?.value),currency,countryName:COUNTRY_CURRENCY[countryCode as keyof typeof COUNTRY_CURRENCY].name}}
 async updateFreeMaryajSettings(u:Principal,dto:{countryCode:string;minimumAmount:string;freeTicketCount:number;payoutAmount?:string|null}){const tenantId=this.tenant(u),countryCode=dto.countryCode.trim().toUpperCase(),currency=currencyForCountry(countryCode),value=validateFreeMaryajPolicy(dto);if(!currency)throw new BadRequestException('UNSUPPORTED_COUNTRY');if(!value)throw new BadRequestException('INVALID_FREE_MARYAJ_SETTINGS');return prisma.$transaction(async tx=>{const latest=await tx.lotteryRule.findFirst({where:{tenantId,jurisdictionCode:countryCode,key:'free_maryaj_policy'},orderBy:{effectiveFrom:'desc'}});const effectiveFrom=new Date(Math.max(Date.now(),(latest?.effectiveFrom.getTime()??0)+1));if(latest?.active)await tx.lotteryRule.updateMany({where:{id:latest.id,tenantId,active:true},data:{active:false,effectiveTo:effectiveFrom}});const rule=await tx.lotteryRule.create({data:{tenantId,jurisdictionCode:countryCode,key:'free_maryaj_policy',value:value as Prisma.InputJsonValue,effectiveFrom}});await tx.auditLog.create({data:{tenantId,userId:u.sub,action:'UPDATE',entityType:'FreeMaryajPolicy',entityId:rule.id,newValues:{countryCode,...value}}});return{countryCode,...value,currency,countryName:COUNTRY_CURRENCY[countryCode as keyof typeof COUNTRY_CURRENCY].name}},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
 games(u:Principal){const tenantId=this.tenant(u);return prisma.game.findMany({where:{tenantId,archivedAt:null},include:{betTypes:{include:{betType:true}},schedules:true,odds:true},orderBy:{name:'asc'}})}
 createGame(u:Principal,dto:{code:string;name:string;description?:string;cutoffSeconds:number;resultDigits:number}){const tenantId=this.tenant(u);return this.auditedCreate(tenantId,u.sub,'Game',()=>prisma.game.create({data:{tenantId,...dto}}))}
 async updateGame(u:Principal,id:string,dto:{name?:string;logoUrl?:string}){const tenantId=this.tenant(u);if(!dto.name&&!dto.logoUrl)throw new BadRequestException('NO_GAME_CHANGES');const old=await prisma.game.findFirst({where:{id,tenantId},select:{name:true,logoUrl:true}});if(!old)throw new ForbiddenException('RESOURCE_NOT_FOUND');const changed=await prisma.game.updateMany({where:{id,tenantId},data:dto});if(changed.count!==1)throw new BadRequestException('GAME_CONCURRENTLY_MODIFIED');await prisma.auditLog.create({data:{tenantId,userId:u.sub,action:'UPDATE',entityType:'Game',entityId:id,oldValues:old,newValues:dto}});return prisma.game.findFirstOrThrow({where:{id,tenantId}})}
 createMarket(u:Principal,dto:{code:string;name:string}){const tenantId=this.tenant(u);return this.auditedCreate(tenantId,u.sub,'Market',()=>prisma.market.create({data:{tenantId,...dto}}))}
 async createSchedule(u:Principal,dto:{gameId:string;marketId?:string;weekday:number;opensAt:string;closesAt:string;resultAt:string;timezone:string}){const tenantId=this.tenant(u);const game=await prisma.game.findFirst({where:{id:dto.gameId,tenantId}});const market=dto.marketId?await prisma.market.findFirst({where:{id:dto.marketId,tenantId}}):null;if(!game||(dto.marketId&&!market))throw new ForbiddenException('RESOURCE_NOT_FOUND');assertScheduleTimes(dto.opensAt,dto.closesAt,dto.resultAt);return this.auditedCreate(tenantId,u.sub,'GameSchedule',()=>prisma.gameSchedule.create({data:{tenantId,...dto}}))}
 createBetType(u:Principal,dto:{code:string;name:string;selectionCount:number;numberMin:number;numberMax:number;allowRepeats:boolean}){const tenantId=this.tenant(u);if(dto.numberMax<dto.numberMin)throw new BadRequestException('INVALID_NUMBER_RANGE');return this.auditedCreate(tenantId,u.sub,'BetType',()=>prisma.betType.create({data:{tenantId,...dto}}))}
 async attachBetType(u:Principal,gameId:string,betTypeId:string){const tenantId=this.tenant(u);const [game,bet]=await Promise.all([prisma.game.findFirst({where:{id:gameId,tenantId}}),prisma.betType.findFirst({where:{id:betTypeId,tenantId}})]);if(!game||!bet)throw new ForbiddenException('RESOURCE_NOT_FOUND');return prisma.gameBetType.upsert({where:{gameId_betTypeId:{gameId,betTypeId}},update:{active:true},create:{gameId,betTypeId}})}
 async draws(u:Principal,from?:string,to?:string){const tenantId=this.tenant(u),dateRange=drawDateFilter(from,to);const where={tenantId,...(dateRange?{drawDate:dateRange}:{})};const [draws,merchant]=await Promise.all([prisma.draw.findMany({where,include:{game:true},orderBy:{opensAt:'desc'},take:200}),prisma.merchantAccount.findFirst({where:{tenantId,userId:u.sub,status:'ACTIVE'},select:{id:true}})]);const gameIds=[...new Set(draws.map(draw=>draw.gameId))];const schedules=gameIds.length?await prisma.gameSchedule.findMany({where:{tenantId,gameId:{in:gameIds}},select:{gameId:true,weekday:true,resultAt:true,active:true}}):[];const rows=draws.map(draw=>({ ...draw, scheduleEnabled:isDrawScheduleEnabled(draw,schedules) }));return merchant?rows.filter(draw=>draw.status!=='OPEN'||draw.scheduleEnabled):rows}
 limits(u:Principal){const tenantId=this.tenant(u);return prisma.bettingLimit.findMany({where:{tenantId,scope:'NUMBER'},include:{game:{select:{name:true}},betType:{select:{name:true,code:true}}},orderBy:{startsAt:'desc'},take:200})}
 async createDraw(u:Principal,dto:{gameId:string;drawNumber:string;drawDate:string;opensAt:string;closesAt:string;resultAt:string}){const tenantId=this.tenant(u);const game=await prisma.game.findFirst({where:{id:dto.gameId,tenantId,status:'ACTIVE'}});if(!game)throw new ForbiddenException('RESOURCE_NOT_FOUND');const opensAt=new Date(dto.opensAt),closesAt=new Date(dto.closesAt),resultAt=new Date(dto.resultAt);assertDrawTimes(opensAt,closesAt,resultAt);return this.auditedCreate(tenantId,u.sub,'Draw',()=>prisma.draw.create({data:{tenantId,gameId:game.id,drawNumber:dto.drawNumber,drawDate:new Date(dto.drawDate),opensAt,closesAt,resultAt,createdById:u.sub}}))}
 async transition(u:Principal,id:string,next:DrawStatus,result?:Record<string,unknown>){const tenantId=this.tenant(u);if(next==='RESULT_PUBLISHED')throw new BadRequestException('USE_RESULT_PUBLISH_ENDPOINT');return prisma.$transaction(async tx=>{const draw=await tx.draw.findFirst({where:{id,tenantId}});if(!draw)throw new ForbiddenException('RESOURCE_NOT_FOUND');if(draw.status===next)return draw;assertDrawTransition(draw.status,next);const changed=await tx.draw.updateMany({where:{id,tenantId,status:draw.status},data:{status:next,result:result as Prisma.InputJsonValue|undefined}});if(changed.count!==1)throw new BadRequestException('DRAW_CONCURRENTLY_MODIFIED');const auditValues={status:next,...(result?{result}:{})}as Prisma.InputJsonValue;await tx.auditLog.create({data:{tenantId,userId:u.sub,action:'UPDATE',entityType:'Draw',entityId:id,oldValues:{status:draw.status},newValues:auditValues}});return tx.draw.findUniqueOrThrow({where:{id}})})}
async createOdds(u:Principal,dto:{gameId:string;betTypeId:string;multiplier:string;startsAt:string;endsAt?:string;resultPosition?:number}){const tenantId=this.tenant(u);const attached=await prisma.gameBetType.findFirst({where:{gameId:dto.gameId,betTypeId:dto.betTypeId,active:true,game:{tenantId},betType:{tenantId}},include:{betType:true}});if(!attached)throw new BadRequestException('BET_TYPE_NOT_ENABLED_FOR_GAME');if(!Number.isFinite(Number(dto.multiplier))||Number(dto.multiplier)<=0)throw new BadRequestException('INVALID_ODDS');if(dto.resultPosition!==undefined)assertPositionedOddsType(attached.betType.code,dto.resultPosition);return prisma.oddsRule.create({data:{tenantId,gameId:dto.gameId,betTypeId:dto.betTypeId,resultPosition:dto.resultPosition,multiplier:dto.multiplier,startsAt:new Date(dto.startsAt),endsAt:dto.endsAt?new Date(dto.endsAt):undefined}})}
 async updateBoletPayouts(u:Principal,dto:{gameId:string;multipliers:string[]}){const tenantId=this.tenant(u);const multipliers=normalizeBoletMultipliers(dto.multipliers);const attached=await prisma.gameBetType.findFirst({where:{gameId:dto.gameId,active:true,game:{tenantId},betType:{tenantId,code:'BOLET'}},include:{betType:true}});if(!attached)throw new BadRequestException('BOLET_NOT_ENABLED_FOR_GAME');const now=new Date();const activeWhere:Prisma.OddsRuleWhereInput={tenantId,gameId:dto.gameId,betTypeId:attached.betTypeId,active:true,resultPosition:{in:[1,2,3]},startsAt:{lte:now},OR:[{endsAt:null},{endsAt:{gt:now}}]};return prisma.$transaction(async tx=>{const oldRules=await tx.oddsRule.findMany({where:activeWhere});await tx.oddsRule.updateMany({where:activeWhere,data:{endsAt:now}});for(let index=0;index<3;index++)await tx.oddsRule.create({data:{tenantId,gameId:dto.gameId,betTypeId:attached.betTypeId,resultPosition:index+1,multiplier:multipliers[index],startsAt:now}});await tx.auditLog.create({data:{tenantId,userId:u.sub,action:'UPDATE',entityType:'BoletPayouts',entityId:dto.gameId,oldValues:{multipliers:oldRules.map(rule=>({position:rule.resultPosition,multiplier:rule.multiplier.toString()}))},newValues:{multipliers}}});return{gameId:dto.gameId,betTypeId:attached.betTypeId,multipliers}},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
 async blockNumber(u:Principal,dto:{gameId?:string;betTypeId?:string;numberKey:string;startsAt?:string;endsAt?:string}){const tenantId=this.tenant(u);const game=dto.gameId?await prisma.game.findFirst({where:{id:dto.gameId,tenantId,status:'ACTIVE'}}):null;if(dto.gameId&&!game)throw new ForbiddenException('RESOURCE_NOT_FOUND');const betTypeId=dto.betTypeId?((await prisma.betType.findFirst({where:{id:dto.betTypeId,tenantId,active:true}}))?.id):undefined;if(dto.betTypeId&&!betTypeId)throw new ForbiddenException('RESOURCE_NOT_FOUND');const numberKey=dto.numberKey.trim();if(!/^\d{1,5}(?:-\d{1,5})?(?:@(?:1|2|3))?$/.test(numberKey))throw new BadRequestException('INVALID_BLOCKED_NUMBER');return prisma.bettingLimit.create({data:{tenantId,scope:'NUMBER',gameId:game?.id,betTypeId,numberKey,minStake:'0',maxStake:'0',startsAt:dto.startsAt?new Date(dto.startsAt):new Date(),endsAt:dto.endsAt?new Date(dto.endsAt):undefined}})}
 async setLimitStatus(u:Principal,id:string,active:boolean){const tenantId=this.tenant(u);const changed=await prisma.bettingLimit.updateMany({where:{id,tenantId,scope:'NUMBER'},data:{active}});if(changed.count!==1)throw new ForbiddenException('RESOURCE_NOT_FOUND');return{id,active}}
 createLimit(u:Principal,dto:{scope:LimitScope;scopeId?:string;gameId?:string;drawId?:string;betTypeId?:string;numberKey?:string;minStake?:string;maxStake?:string;maxExposure?:string;startsAt:string}){const tenantId=this.tenant(u);if(dto.minStake&&dto.maxStake&&Number(dto.maxStake)<Number(dto.minStake))throw new BadRequestException('INVALID_LIMIT_RANGE');return prisma.bettingLimit.create({data:{tenantId,...dto,startsAt:new Date(dto.startsAt)}})}
 createRule(u:Principal,dto:{jurisdictionCode:string;key:string;value:Record<string,unknown>;effectiveFrom:string;effectiveTo?:string}){const tenantId=this.tenant(u);return this.auditedCreate(tenantId,u.sub,'LotteryRule',()=>prisma.lotteryRule.create({data:{tenantId,jurisdictionCode:dto.jurisdictionCode,key:dto.key,value:dto.value as Prisma.InputJsonValue,effectiveFrom:new Date(dto.effectiveFrom),effectiveTo:dto.effectiveTo?new Date(dto.effectiveTo):undefined}}))}
 private async auditedCreate<T extends{id:string}>(tenantId:string,userId:string,entityType:string,create:()=>Promise<T>){const entity=await create();await prisma.auditLog.create({data:{tenantId,userId,action:'CREATE',entityType,entityId:entity.id}});return entity}
 private async syncUpcomingScheduledDraws(tx:Prisma.TransactionClient,tenantId:string,gameId:string,schedules:ScheduleDrawTiming[]){if(!schedules.length)return 0;const game=await tx.game.findFirst({where:{id:gameId,tenantId},select:{code:true}});if(!game)return 0;const now=new Date(),draws=await tx.draw.findMany({where:{tenantId,gameId,status:'SCHEDULED',resultAt:{gt:now}},select:{id:true,drawNumber:true,status:true,opensAt:true,closesAt:true,resultAt:true}});let updated=0;for(const draw of draws){const next=schedules.map(schedule=>scheduledDrawTimeUpdate(draw,schedule,game.code,now)).find(Boolean);if(!next)continue;if(draw.drawNumber===next.drawNumber&&draw.opensAt.getTime()===next.opensAt.getTime()&&draw.closesAt.getTime()===next.closesAt.getTime()&&draw.resultAt.getTime()===next.resultAt.getTime())continue;const changed=await tx.draw.updateMany({where:{id:draw.id,tenantId,status:'SCHEDULED',drawNumber:draw.drawNumber,opensAt:draw.opensAt,closesAt:draw.closesAt,resultAt:draw.resultAt},data:next});updated+=changed.count}return updated}
 private tenant(u:Principal){if(!u.tenantId)throw new ForbiddenException('TENANT_ACCESS_REQUIRED');return u.tenantId}
}
