import type{PrinterDriver,PrinterStatus,PrinterTransport,TicketPrintData,TicketTemplate}from'./types.js';
const enc=new TextEncoder();const cmd=(...bytes:number[])=>new Uint8Array(bytes);const concat=(parts:Uint8Array[])=>{const size=parts.reduce((n,x)=>n+x.length,0),out=new Uint8Array(size);let offset=0;for(const part of parts){out.set(part,offset);offset+=part.length}return out};
export class EscPosDriver implements PrinterDriver{private connected=false;constructor(private transport:PrinterTransport){}async connect(){await this.transport.open();this.connected=true;await this.transport.write(cmd(0x1b,0x40))}async disconnect(){await this.transport.close();this.connected=false}async status():Promise<PrinterStatus>{return this.transport.status?this.transport.status():{state:this.connected?'READY':'DISCONNECTED'}}async print(data:Uint8Array){if(!this.connected)throw new Error('PRINTER_NOT_CONNECTED');await this.transport.write(data)}async testPrint(){await this.print(enc.encode('TES ENPRIMANT\nTEST OK\n\n'))}async cashDrawer(){await this.print(cmd(0x1b,0x70,0,25,250))}async cut(){await this.print(cmd(0x1d,0x56,0))}async feed(lines:number){await this.print(cmd(0x1b,0x64,Math.max(0,Math.min(255,lines))))}}
const line=(left:string,right:string,width:number)=>{const gap=Math.max(1,width-left.length-right.length);return`${left}${' '.repeat(gap)}${right}\n`};
const centered=(value:string)=>concat([cmd(0x1b,0x61,1),enc.encode(value+'\n'),cmd(0x1b,0x61,0)]);
const barcode=(value:string)=>{const data=enc.encode(value.slice(0,250));return concat([cmd(0x1d,0x48,2,0x1d,0x68,70,0x1d,0x77,2,0x1d,0x6b,73,data.length),data,cmd(10)])};
const qr=(value:string)=>{const data=enc.encode(value),length=data.length+3;return concat([cmd(0x1d,0x28,0x6b,4,0,49,65,50,0,0x1d,0x28,0x6b,3,0,49,67,4,0x1d,0x28,0x6b,3,0,49,69,49,0x1d,0x28,0x6b,length&255,length>>8,49,80,48),data,cmd(0x1d,0x28,0x6b,3,0,49,81,48,10)])};
export function renderTicket(template:TicketTemplate,data:TicketPrintData):Uint8Array{
 const width=template.paperWidth===80?48:32,name=data.businessName?.trim();
 if(!name||/^lottivexa$/i.test(name))throw new Error('RECEIPT_BUSINESS_NAME_REQUIRED');
 const currency=data.currency||'HTG';
 const safeHeader=template.header&&!/lottivexa/i.test(template.header)?template.header:'';
 const body:string[]=[`${name.slice(0,width)}\n`,'FICH BOLET\n',safeHeader?`${safeHeader.slice(0,width)}\n`:'',`TIKE ${data.ticketNumber}\n`,`LOTRI: ${data.game}\n`,`TIRAJ: ${data.draw}\n`,data.branch?`BIWO: ${data.branch}\n`:'',data.branchAddress?`${data.branchAddress}\n`:'',data.branchPhone?`TELEFÒN: ${data.branchPhone}\n`:'',data.merchant?`MACHANN: ${data.merchant}${data.merchantNumber?` · ${data.merchantNumber}`:''}\n`:'',`DAT / LÈ: ${data.createdAt}\n`,'-'.repeat(width)+'\n'];
 const parts=[cmd(0x1b,0x40,0x1b,0x61,1,0x1b,0x45,1),enc.encode(body[0]+body[1]),cmd(0x1b,0x45,0,0x1b,0x61,0),enc.encode(body.slice(2).join(''))];
 for(const item of data.lines){const[rawSelection,position]=item.selection.split('@');const selection=rawSelection.replaceAll('-',' × ');parts.push(enc.encode(`${(item.betType||'JWÈT').slice(0,width)}\n`),enc.encode(line(selection,item.isPromotional?'GRATIS':`${currency} ${item.stake}`,width)));if(position)parts.push(centered(`OP ${position}`));if((item.winCount??0)>1)parts.push(enc.encode(`DEKABÈS × ${item.winCount}\n`));if(item.isPromotional)parts.push(enc.encode('Liy bonus gratis\n'));if(item.isWinner)parts.push(enc.encode(`GANYEN: ${currency} ${item.potentialWin}\n`))}
 parts.push(enc.encode('-'.repeat(width)+'\n'),enc.encode(line('TOTAL',`${currency} ${data.amount}`,width)),enc.encode(line('GANY POSIB',`${currency} ${data.potentialWin}`,width)),enc.encode(`ESTATI: ${data.status||'VALID'}\n`));
 if(Number(data.winningAmount)>0)parts.push(enc.encode(line('GANY KONFIME',`${currency} ${data.winningAmount}`,width)));
 parts.push(enc.encode(`DAT: ${data.createdAt}\n`),enc.encode(template.footer&&!/lottivexa/i.test(template.footer)?`${template.footer.slice(0,width)}\n`:'Kenbe tikè orijinal la. Verifye avan peman.\n'));
 if(template.showBarcode)parts.push(barcode(data.barcode));if(template.showQr)parts.push(qr(data.qrCode));parts.push(cmd(10));return concat(parts)
}
