import 'package:flutter/material.dart';
import '../../core/network/api_client.dart';
import '../../core/security/session_store.dart';
class AdminResourceScreen extends StatefulWidget { const AdminResourceScreen({super.key,required this.api,required this.session,required this.resource});final ApiClient api;final SessionStore session;final String resource;@override State<AdminResourceScreen>createState()=>_AdminResourceState(); }
class _AdminResourceState extends State<AdminResourceScreen>{
 List<Map<String,dynamic>>rows=[];bool loading=true;String?error;
 static const definitions=<String,({String title,String endpoint})>{'merchants':(title:'Merchants',endpoint:'/api/v1/merchants'),'branches':(title:'Branches',endpoint:'/api/v1/branches'),'users':(title:'Users',endpoint:'/api/v1/users'),'devices':(title:'Devices',endpoint:'/api/v1/devices'),'printers':(title:'Printers',endpoint:'/api/v1/printing/printers'),'finance':(title:'Trial Balance',endpoint:'/api/v1/finance/trial-balance')};
 @override void initState(){super.initState();load();}
 Future<void>load()async{setState(()=>loading=true);final definition=definitions[widget.resource];if(definition==null){setState((){error='Seksyon admin sa a pa egziste.';loading=false;});return;}try{final response=await widget.api.dio.get<List<dynamic>>(definition.endpoint);if(mounted)setState((){rows=(response.data??[]).map((x)=>Map<String,dynamic>.from(x as Map)).toList();error=null;loading=false;});}catch(_){if(mounted)setState((){error='Done yo pa kapab chaje oswa plan/wòl la pa bay aksè.';loading=false;});}}
 Future<void>deviceAction(String id,String action)async{try{await widget.api.dio.post('/api/v1/devices/$id/$action');await load();}catch(_){notice('Aksyon device la pa pase.');}}
 Future<void>editDevice(Map<String,dynamic>row)async{final name=TextEditingController(text:row['name']?.toString()),branch=TextEditingController(text:row['branchId']?.toString()),merchant=TextEditingController(text:row['merchantId']?.toString()??'');final save=await showDialog<bool>(context:context,builder:(context)=>AlertDialog(title:const Text('Rename / reassign device'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:name,decoration:const InputDecoration(labelText:'Device name')),TextField(controller:branch,decoration:const InputDecoration(labelText:'Branch ID')),TextField(controller:merchant,decoration:const InputDecoration(labelText:'Merchant ID (optional)'))])),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Save'))]));if(save!=true)return;try{await widget.api.dio.patch('/api/v1/devices/${row['id']}',data:{'name':name.text.trim(),'branchId':branch.text.trim(),'merchantId':merchant.text.trim().isEmpty?null:merchant.text.trim()});await load();}catch(_){notice('Device la pa modifye. Verifye branch ak merchant IDs yo.');}}
 Future<void>editMerchant(Map<String,dynamic>row)async{if(!widget.session.hasPermission('merchants.edit'))return;final user=Map<String,dynamic>.from((row['user'] as Map?) ?? {}),name=TextEditingController(text:row['displayName']?.toString()),username=TextEditingController(text:user['username']?.toString()),phone=TextEditingController(text:user['phone']?.toString()??''),email=TextEditingController(text:user['email']?.toString()??''),branch=TextEditingController(text:row['branchId']?.toString());final save=await showDialog<bool>(context:context,builder:(context)=>AlertDialog(title:const Text('Edit merchant'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:name,decoration:const InputDecoration(labelText:'Display name')),TextField(controller:username,decoration:const InputDecoration(labelText:'Username')),TextField(controller:phone,decoration:const InputDecoration(labelText:'Phone')),TextField(controller:email,decoration:const InputDecoration(labelText:'Email')),TextField(controller:branch,decoration:const InputDecoration(labelText:'Branch ID'))])),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Save'))]));if(save!=true)return;try{await widget.api.dio.patch('/api/v1/merchants/${row['id']}',data:{'displayName':name.text.trim(),'username':username.text.trim(),'phone':phone.text.trim(),'email':email.text.trim(),'branchId':branch.text.trim()});await load();}catch(_){notice('Merchant la pa modifye. Verifye done yo ak branch lan.');}}
 Future<void>editUser(Map<String,dynamic>row)async{if(!widget.session.hasPermission('users.edit'))return;final available=await widget.api.dio.get<List<dynamic>>('/api/v1/roles'),roles=(available.data??[]).map((x)=>Map<String,dynamic>.from(x as Map)).toList(),username=TextEditingController(text:row['username']?.toString()),email=TextEditingController(text:row['email']?.toString()??''),phone=TextEditingController(text:row['phone']?.toString()??''),roleIds=TextEditingController(text:((row['roles'] as List?) ?? []).map((x)=>(x as Map)['roleId']).join(','));if(!mounted)return;final save=await showDialog<bool>(context:context,builder:(context)=>AlertDialog(title:const Text('Edit user'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:username,decoration:const InputDecoration(labelText:'Username')),TextField(controller:email,decoration:const InputDecoration(labelText:'Email')),TextField(controller:phone,decoration:const InputDecoration(labelText:'Phone')),Text('Available roles: ${roles.map((x)=>'${x['name']}=${x['id']}').join(' | ')}'),TextField(controller:roleIds,decoration:const InputDecoration(labelText:'Role IDs, comma-separated'))])),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Save'))]));if(save!=true)return;try{await widget.api.dio.patch('/api/v1/users/${row['id']}',data:{'username':username.text.trim(),'email':email.text.trim(),'phone':phone.text.trim(),'roleIds':roleIds.text.split(',').map((x)=>x.trim()).where((x)=>x.isNotEmpty).toList()});await load();}catch(_){notice('User la pa modifye. Verifye done ak roles yo.');}}
 void notice(String text){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(text)));}
 String rowTitle(Map<String,dynamic>r)=>switch(widget.resource){'merchants'=>r['displayName']?.toString()??'Merchant','branches'=>r['name']?.toString()??'Branch','users'=>r['username']?.toString()??'User','devices'=>r['name']?.toString()??'Device','printers'=>r['name']?.toString()??'Printer','finance'=>'${r['code']??''} ${r['name']??''}',_=>'Record'};
 String subtitle(Map<String,dynamic>r)=>switch(widget.resource){'merchants'=>'${r['merchantNumber']??''} • ${r['branch']?['name']??''} • ${r['status']??''}','branches'=>'${r['code']??''} • ${r['status']??''} • ${r['_count']?['merchants']??0} merchants','users'=>'${r['email']??r['phone']??''} • ${r['status']??''}','devices'=>'${r['platform']??''} • ${r['status']??''} • ${r['branch']?['name']??''}','printers'=>'${r['connectionType']??''} • ${r['status']??''} • ${r['branch']?['name']??''}','finance'=>'Debit ${r['debit']??0} • Credit ${r['credit']??0} • Balance ${r['balance']??0}',_=>''};
 bool hasDeviceAction(Map<String,dynamic>r)=>widget.session.hasPermission('devices.register')||widget.session.hasPermission('devices.disable');
 @override Widget build(BuildContext context){final definition=definitions[widget.resource];if(definition==null)return const Scaffold(body:Center(child:Text('Unknown admin resource')));return Scaffold(appBar:AppBar(title:Text(definition.title)),body:RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(16),children:[if(loading)const LinearProgressIndicator(),if(error!=null)Card(child:ListTile(leading:const Icon(Icons.error_outline),title:Text(error!))),if(!loading&&error==null&&rows.isEmpty)const Card(child:ListTile(title:Text('Pa gen okenn record pou seksyon sa a.'))),...rows.map((r)=>Card(child:ListTile(title:Text(rowTitle(r)),subtitle:Text(subtitle(r)),onTap:widget.resource=='merchants'&&widget.session.hasPermission('merchants.edit')?()=>editMerchant(r):widget.resource=='users'&&widget.session.hasPermission('users.edit')?()=>editUser(r):null,trailing:widget.resource=='devices'&&hasDeviceAction(r)?PopupMenuButton<String>(onSelected:(value){if(value=='edit'){editDevice(r);}else{deviceAction(r['id'].toString(),value);}},itemBuilder:(_)=>[if(widget.session.hasPermission('devices.register'))const PopupMenuItem(value:'edit',child:Text('Rename / Reassign')),if(widget.session.hasPermission('devices.register')&&r['status']=='PENDING')const PopupMenuItem(value:'approve',child:Text('Approve')),if(widget.session.hasPermission('devices.disable')&&r['status']=='BLOCKED')const PopupMenuItem(value:'unblock',child:Text('Unblock')),if(widget.session.hasPermission('devices.disable')&&r['status']!='BLOCKED')const PopupMenuItem(value:'block',child:Text('Block'))]):null)))])));}
}
