export const COUNTRIES: [string, string][] = [
  ["HT", "Haiti · HTG"],
  ["US", "United States · USD"],
  ["CA", "Canada · CAD"],
  ["DO", "Dominican Republic · DOP"],
  ["JM", "Jamaica · JMD"],
  ["BS", "Bahamas · BSD"],
  ["BB", "Barbados · BBD"],
  ["BZ", "Belize · BZD"],
  ["TT", "Trinidad and Tobago · TTD"],
  ["GY", "Guyana · GYD"],
  ["SR", "Suriname · SRD"],
  ["MX", "Mexico · MXN"],
  ["BR", "Brazil · BRL"],
  ["AR", "Argentina · ARS"],
  ["BO", "Bolivia · BOB"],
  ["CL", "Chile · CLP"],
  ["CO", "Colombia · COP"],
  ["CR", "Costa Rica · CRC"],
  ["CU", "Cuba · CUP"],
  ["EC", "Ecuador · USD"],
  ["SV", "El Salvador · USD"],
  ["GT", "Guatemala · GTQ"],
  ["HN", "Honduras · HNL"],
  ["NI", "Nicaragua · NIO"],
  ["PA", "Panama · USD"],
  ["PY", "Paraguay · PYG"],
  ["PE", "Peru · PEN"],
  ["UY", "Uruguay · UYU"],
  ["VE", "Venezuela · VES"],
  ["PR", "Puerto Rico · USD"],
  ["GB", "United Kingdom · GBP"],
  ["FR", "France · EUR"],
  ["ES", "Spain · EUR"],
  ["DE", "Germany · EUR"],
  ["PT", "Portugal · EUR"],
  ["IT", "Italy · EUR"],
  ["NL", "Netherlands · EUR"],
  ["BE", "Belgium · EUR"],
  ["CH", "Switzerland · CHF"],
  ["IE", "Ireland · EUR"],
  ["AU", "Australia · AUD"],
  ["NZ", "New Zealand · NZD"],
  ["JP", "Japan · JPY"],
  ["CN", "China · CNY"],
  ["IN", "India · INR"],
  ["PH", "Philippines · PHP"],
  ["NG", "Nigeria · NGN"],
  ["GH", "Ghana · GHS"],
  ["ZA", "South Africa · ZAR"],
];
