CREATE EXTENSION IF NOT EXISTS citext;
CREATE TYPE "TenantStatus" AS ENUM ('PROVISIONING','ACTIVE','SUSPENDED','ARCHIVED');
CREATE TYPE "SubscriptionStatus" AS ENUM ('TRIAL','ACTIVE','PAST_DUE','EXPIRED','SUSPENDED','CANCELLED');
CREATE TYPE "BillingInterval" AS ENUM ('MONTHLY','YEARLY');
CREATE TYPE "UserStatus" AS ENUM ('INVITED','ACTIVE','DISABLED','LOCKED');
CREATE TYPE "DomainVerification" AS ENUM ('PENDING','VERIFIED','FAILED');
CREATE TYPE "SslStatus" AS ENUM ('PENDING','ACTIVE','FAILED');
CREATE TABLE "Tenant" ("id" UUID PRIMARY KEY,"slug" VARCHAR(63) NOT NULL UNIQUE,"legalName" VARCHAR(200) NOT NULL,"status" "TenantStatus" NOT NULL DEFAULT 'PROVISIONING',"jurisdictionCode" VARCHAR(20),"createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),"archivedAt" TIMESTAMPTZ);
CREATE TABLE "User" ("id" UUID PRIMARY KEY,"tenantId" UUID,"email" CITEXT,"phone" VARCHAR(32),"username" CITEXT NOT NULL,"passwordHash" TEXT NOT NULL,"status" "UserStatus" NOT NULL DEFAULT 'INVITED',"forcePasswordChange" BOOLEAN NOT NULL DEFAULT true,"twoFactorEnabled" BOOLEAN NOT NULL DEFAULT false,"tokenVersion" INTEGER NOT NULL DEFAULT 0,"lastLoginAt" TIMESTAMPTZ,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),"deletedAt" TIMESTAMPTZ,CONSTRAINT "User_tenant_fk" FOREIGN KEY("tenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT,UNIQUE("tenantId","username"),UNIQUE("tenantId","email"));
CREATE TABLE "Role" ("id" UUID PRIMARY KEY,"tenantId" UUID,"code" VARCHAR(80) NOT NULL,"name" VARCHAR(120) NOT NULL,"isSystem" BOOLEAN NOT NULL DEFAULT false,FOREIGN KEY("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE,UNIQUE("tenantId","code"));
CREATE TABLE "Permission" ("id" UUID PRIMARY KEY,"code" VARCHAR(100) NOT NULL UNIQUE,"description" TEXT);
CREATE TABLE "RolePermission" ("roleId" UUID NOT NULL REFERENCES "Role"("id") ON DELETE CASCADE,"permissionId" UUID NOT NULL REFERENCES "Permission"("id") ON DELETE CASCADE,PRIMARY KEY("roleId","permissionId"));
CREATE TABLE "UserRole" ("userId" UUID NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,"roleId" UUID NOT NULL REFERENCES "Role"("id") ON DELETE CASCADE,PRIMARY KEY("userId","roleId"));
CREATE TABLE "Plan" ("id" UUID PRIMARY KEY,"code" VARCHAR(60) NOT NULL UNIQUE,"name" VARCHAR(120) NOT NULL,"monthlyPrice" NUMERIC(19,4) NOT NULL,"yearlyPrice" NUMERIC(19,4) NOT NULL,"currency" CHAR(3) NOT NULL,"trialDays" INTEGER NOT NULL DEFAULT 0,"maxMerchants" INTEGER,"maxBranches" INTEGER,"maxDevices" INTEGER,"maxTickets" BIGINT,"storageLimitBytes" BIGINT,"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE "PlanFeature" ("planId" UUID NOT NULL REFERENCES "Plan"("id") ON DELETE CASCADE,"key" VARCHAR(100) NOT NULL,"enabled" BOOLEAN NOT NULL DEFAULT false,"config" JSONB,PRIMARY KEY("planId","key"));
CREATE TABLE "Subscription" ("id" UUID PRIMARY KEY,"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE RESTRICT,"planId" UUID NOT NULL REFERENCES "Plan"("id") ON DELETE RESTRICT,"status" "SubscriptionStatus" NOT NULL,"interval" "BillingInterval" NOT NULL,"startsAt" TIMESTAMPTZ NOT NULL,"currentPeriodEndsAt" TIMESTAMPTZ NOT NULL,"graceEndsAt" TIMESTAMPTZ,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE "TenantSetting" ("tenantId" UUID PRIMARY KEY REFERENCES "Tenant"("id") ON DELETE CASCADE,"currency" CHAR(3) NOT NULL,"timezone" TEXT NOT NULL DEFAULT 'UTC',"locale" TEXT NOT NULL DEFAULT 'ht',"dateFormat" TEXT NOT NULL DEFAULT 'yyyy-MM-dd');
CREATE TABLE "TenantBranding" ("tenantId" UUID PRIMARY KEY REFERENCES "Tenant"("id") ON DELETE CASCADE,"businessName" TEXT NOT NULL,"logoUrl" TEXT,"faviconUrl" TEXT,"primaryColor" TEXT NOT NULL DEFAULT '#172554',"secondaryColor" TEXT NOT NULL DEFAULT '#f59e0b');
CREATE TABLE "TenantDomain" ("id" UUID PRIMARY KEY,"tenantId" UUID NOT NULL REFERENCES "Tenant"("id") ON DELETE CASCADE,"domain" CITEXT NOT NULL UNIQUE,"verificationStatus" "DomainVerification" NOT NULL DEFAULT 'PENDING',"sslStatus" "SslStatus" NOT NULL DEFAULT 'PENDING',"isPrimary" BOOLEAN NOT NULL DEFAULT false,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE UNIQUE INDEX "one_primary_domain_per_tenant" ON "TenantDomain"("tenantId") WHERE "isPrimary" = true;
CREATE TABLE "RefreshToken" ("id" UUID PRIMARY KEY,"userId" UUID NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,"tokenHash" TEXT NOT NULL UNIQUE,"deviceId" TEXT,"expiresAt" TIMESTAMPTZ NOT NULL,"revokedAt" TIMESTAMPTZ,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE "AuditLog" ("id" BIGSERIAL PRIMARY KEY,"tenantId" UUID REFERENCES "Tenant"("id") ON DELETE RESTRICT,"userId" UUID REFERENCES "User"("id") ON DELETE SET NULL,"action" VARCHAR(100) NOT NULL,"entityType" VARCHAR(100) NOT NULL,"entityId" TEXT,"oldValues" JSONB,"newValues" JSONB,"ipAddress" INET,"deviceId" TEXT,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX "audit_tenant_time" ON "AuditLog"("tenantId","createdAt" DESC);
CREATE INDEX "subscription_enforcement" ON "Subscription"("tenantId","status","currentPeriodEndsAt");
CREATE INDEX "user_tenant_status" ON "User"("tenantId","status");

ALTER TABLE "Tenant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Role" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Subscription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TenantSetting" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TenantBranding" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TenantDomain" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_user_isolation ON "User" USING ("tenantId" = nullif(current_setting('app.tenant_id', true),'')::uuid OR current_setting('app.is_platform_admin',true)='true');
CREATE POLICY tenant_role_isolation ON "Role" USING ("tenantId" = nullif(current_setting('app.tenant_id', true),'')::uuid OR current_setting('app.is_platform_admin',true)='true');
CREATE POLICY tenant_subscription_isolation ON "Subscription" USING ("tenantId" = nullif(current_setting('app.tenant_id', true),'')::uuid OR current_setting('app.is_platform_admin',true)='true');
CREATE POLICY tenant_settings_isolation ON "TenantSetting" USING ("tenantId" = nullif(current_setting('app.tenant_id', true),'')::uuid OR current_setting('app.is_platform_admin',true)='true');
CREATE POLICY tenant_branding_isolation ON "TenantBranding" USING ("tenantId" = nullif(current_setting('app.tenant_id', true),'')::uuid OR current_setting('app.is_platform_admin',true)='true');
CREATE POLICY tenant_domain_isolation ON "TenantDomain" USING ("tenantId" = nullif(current_setting('app.tenant_id', true),'')::uuid OR current_setting('app.is_platform_admin',true)='true');
CREATE POLICY tenant_audit_isolation ON "AuditLog" USING ("tenantId" = nullif(current_setting('app.tenant_id', true),'')::uuid OR current_setting('app.is_platform_admin',true)='true');
