import{BadRequestException,ForbiddenException,Injectable}from'@nestjs/common';
import{DeviceStatus,prisma,Prisma}from'@lottivexa/database';
import type{Principal}from'../common/guards/jwt-auth.guard';
import{deviceUpdate}from'./device-policy';

type Registration={branchId:string;merchantId?:string;name:string;deviceType:string;platform:string;osVersion?:string;appVersion?:string;publicKey?:string};
@Injectable()export class DevicesService{
  list(u:Principal){return prisma.device.findMany({where:{tenantId:this.tenant(u)},include:{branch:true,merchant:true},orderBy:{createdAt:'desc'}})}
  async register(u:Principal,dto:Registration){const tenantId=this.tenant(u);await this.assignment(tenantId,dto.branchId,dto.merchantId);await this.capacity(tenantId);const device=await prisma.device.create({data:{tenantId,...dto,status:'PENDING'}});await prisma.auditLog.create({data:{tenantId,userId:u.sub,action:'CREATE',entityType:'Device',entityId:device.id,newValues:{branchId:dto.branchId,merchantId:dto.merchantId,name:dto.name}}});return device}
  async update(u:Principal,id:string,input:{branchId?:string;merchantId?:string|null;name?:string}){const tenantId=this.tenant(u),current=await prisma.device.findFirst({where:{id,tenantId}});if(!current)throw new ForbiddenException('RESOURCE_NOT_FOUND');const dto=deviceUpdate(input),branchId=dto.branchId??current.branchId,merchantId=dto.merchantId===undefined?current.merchantId:dto.merchantId;await this.assignment(tenantId,branchId,merchantId??undefined);const changed=await prisma.device.updateMany({where:{id,tenantId},data:{name:dto.name,branchId,merchantId}});if(changed.count!==1)throw new ForbiddenException('RESOURCE_NOT_FOUND');await prisma.auditLog.create({data:{tenantId,userId:u.sub,action:'UPDATE',entityType:'Device',entityId:id,oldValues:{name:current.name,branchId:current.branchId,merchantId:current.merchantId}as Prisma.InputJsonValue,newValues:{name:dto.name??current.name,branchId,merchantId}as Prisma.InputJsonValue}});return this.one(tenantId,id)}
  async status(u:Principal,id:string,status:DeviceStatus){const tenantId=this.tenant(u),changed=await prisma.device.updateMany({where:{id,tenantId},data:{status}});if(changed.count!==1)throw new ForbiddenException('RESOURCE_NOT_FOUND');await prisma.auditLog.create({data:{tenantId,userId:u.sub,action:status==='BLOCKED'?'DEVICE_BLOCK':'UPDATE',entityType:'Device',entityId:id,newValues:{status}}});return{updated:true,status}}
  async unblock(u:Principal,id:string){const tenantId=this.tenant(u),device=await prisma.device.findFirst({where:{id,tenantId}});if(!device)throw new ForbiddenException('RESOURCE_NOT_FOUND');if(device.status!=='BLOCKED')throw new BadRequestException('DEVICE_NOT_BLOCKED');await this.capacity(tenantId);return this.status(u,id,'OFFLINE')}
  private one(tenantId:string,id:string){return prisma.device.findFirstOrThrow({where:{id,tenantId},include:{branch:true,merchant:true}})}
  private async assignment(tenantId:string,branchId:string,merchantId?:string){const branch=await prisma.branch.findFirst({where:{id:branchId,tenantId,status:'ACTIVE'}}),merchant=merchantId?await prisma.merchantAccount.findFirst({where:{id:merchantId,tenantId,branchId,status:'ACTIVE'}}):null;if(!branch||(merchantId&&!merchant))throw new BadRequestException('INVALID_DEVICE_ASSIGNMENT')}
  private async capacity(tenantId:string){const now=new Date(),subscription=await prisma.subscription.findFirstOrThrow({where:{tenantId,OR:[{status:{in:['ACTIVE','TRIAL']},currentPeriodEndsAt:{gt:now}},{status:'PAST_DUE',graceEndsAt:{gt:now}}]},include:{plan:true},orderBy:{createdAt:'desc'}});if(subscription.plan.maxDevices!==null&&await prisma.device.count({where:{tenantId,status:{not:'BLOCKED'}}})>=subscription.plan.maxDevices)throw new ForbiddenException('LIMIT_REACHED')}
  private tenant(u:Principal){if(!u.tenantId)throw new ForbiddenException('TENANT_ACCESS_REQUIRED');return u.tenantId}
}
